### ISSUE TITLE
Layout Problem in Preferences-Dialog

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1008]
die Separator-Captions haben nicht die richtige Höhe:

![grafik](https://user-images.githubusercontent.com/41451972/141807511-b3b05cb3-9bf4-48dd-80fe-ad4d2a013b3c.png)

**Comment by Bauer-David** [comment]
Dieser Fehler ist schon bekannt und wurde bei Nebula direkt von uns behoben. Wir müssen hier auf den Release 2.6.0 von den Nebula Widgets warten.
