### ISSUE TITLE
login dialog should show company or WFC fav-icon

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1011]
![grafik](https://user-images.githubusercontent.com/41451972/141971294-181cc1bc-4555-4a7d-bd90-b79c3eca0778.png)

**Comment by janiak-minova** [comment]
<img width="200" alt="Bildschirmfoto 2021-11-16 um 12 30 32" src="https://user-images.githubusercontent.com/77741125/141977732-87eb8247-3197-42d8-bde3-2801021373d7.png">
Wenn möglich sollte auch die Auflösung in Dock (zumindest unter Mac) vergrößert werden.

**Comment by vogella** [comment]
Sollte mit den Änderung gefixt sein

![image](https://user-images.githubusercontent.com/139910/150110868-39e11866-6576-4b52-95fd-3e586c8f31d0.png)
