### ISSUE TITLE
ungenauer Link zum Parent-pom in pom.xml

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1022]
beim Übernehmen des Projekts in eine andere IDE hat diese verschiedene Warnungen ausgegeben.
Eine davon ist in vielen pom.xml zu finden - überall dort, wo ein Verweis auf eine übergordnete Struktur angegeben ist.
Nachschlagen im Netz hat diese richtige Schreibweise ergeben:

![grafik](https://user-images.githubusercontent.com/41451972/142452903-0893a20b-8b04-4137-9254-2a4db19b7152.png)

**Comment by vogella** [comment]
Soweit ist weiß, kann man den relativePath in diesem Fall auch weglassen.  PR coming....
