### ISSUE TITLE
Kaputte Perspective-Toolbar

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1032]
<img width="358" alt="Bildschirmfoto 2021-11-26 um 13 57 10" src="https://user-images.githubusercontent.com/77741125/143584499-a4df907f-7559-4967-b12a-5b54f8c2dfa9.png">

Das Problem scheint aufzutreten, wenn die Anwendung nicht über das rote Kreuz der Anwendung selbst, sondern z.B. über die Konsole von Eclipse geschlossen wird. Wahrscheinlich werden die Perspektiven nur teilweise persistiert, was beim Neustart zu Problemen führt.

**Comment by wis36** [comment]
Das Persistieren erfolgt normalerweise beim sauberen Schließen der Anwendung.
