### ISSUE TITLE
Kunden- und Anwendungsspezifische Übersetzungen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1035]
Übersetzungen sind teilweise Kunden- bzw. Anwendungstypspezifisch (z.B. "Kunde" statt "Warenempfänger" im SIS).

- [x] Definieren des Kunden- und Anwendungskürzels (z.B. SIS, TTA, ...) in der .xbs
- [x] Auslesen und Nutzen von Kundenspezifischen .properties Datein im i18n Ordner von Seiten der Anwendung -> sollte schon eingebaut sein

**Comment by CE7** [comment]
Hier haben wir einfach einen Kürzel des Kunden an die entsprechenden Property gehängt.

**Comment by CE7** [comment]
Hier ein kleines Beispiel: 

`
 <property name="tRemarks.Remarks.Dispatch.WAHR">
                <default content="Driver"/>
                <value content="Fahrer" lang="de"/>
                <value content="Sürücü" lang="tr"/>
            </property>
`
