### ISSUE TITLE
Grid Bedienung verbessern

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1036]
Die Grids sollten userfreundlicher gestaltet werden.

- [x] Nach Eingabe eines Wertes wird die nächste Zelle (rechts von der Eingabe) ausgewählt
- [x] Navigieren mit den Pfeiltasten ermöglichen
  - [x] Pfeiltastendruck commitet die aktuelle Änderung (auch bei "falscher" Eingabe)
  - [x] Der Editor der Zelle in Richtung der Pfeiltaste wird geöffnet 
- [x] Evtl Wählen der Felder mit Tab (alle) und Enter (Pflichtfelder) 
- [x] Bei Klick in eine Zelle Inhalt komplett markieren, damit dieser gleich überschrieben werden kann
- [x] Bei Lookups in Grids Eingabe von Zahlen unterstützen (siehe Beispiel in Kommentar)

**Comment by Bauer-David** [comment]
Enter-Verhalten reagiert nicht mehr

**Comment by Bauer-David** [comment]
Ergebnis der Besprechung mit SAW, ERC, JAL und BAD:

- Die Navigation innerhalb des Grids soll über eine Preference konfigurierbar sein:

- [ ] Preference für "Navigation mit Tab in Grids" =>**NTG**
- [ ] Tab im Grid springt ein Feld nach rechts  (-> NTG = true)
- [ ] Tab in der letzten Zelle des Grids verlässt das Grid (-> NTG = true)
- [ ] Shift + Tab im Grid springt ein Feld nach links (-> NTG = true)
- [ ]  Shift + Tab in der ersten Zelle des Grids verlässt das Grid
- [ ] Betreten des Grids mit Tab selektiert die erste Zelle im ViewLayer
- [ ] Tab selektiert **nur** die erste Zelle im ViewLayer (-> NTG = false)
- [ ] Tab im Grid verlässt das Grid (-> NTG = true)

- Selbes Enter-Verhalten im Grid wie außerhalb.

- [ ] Enter selektiert das nächste Pflichtfeld entsprechend der Preferences.
- [ ] Enter springt in Pflichtfelder im Grid
- [ ] Enter kann Pflichtfelder außerhalb des Grids selektieren

**Comment by janiak-minova** [comment]
<img width="847" alt="Bildschirmfoto 2021-12-06 um 11 12 55" src="https://user-images.githubusercontent.com/77741125/144828093-f742647a-f6c7-4e36-b2a3-2923bfb5f939.png">
