### ISSUE TITLE
Profile löschen.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#1045]
Ich denke es wäre hilfreich, wenn man in Zukunft Profile löschen könnte.

**Comment by janiak-minova** [comment]
Das kann man schon im Login-Screen über das Mülleimer Icon.

<img width="520" alt="Bildschirmfoto 2021-12-02 um 15 35 57" src="https://user-images.githubusercontent.com/77741125/144442657-f295d5fb-1bb9-4b92-b077-612a6a7e021c.png">

Ist das in Ordnung?
