### ISSUE TITLE
Datumsfeld zu klein für Pattern MMMM.dd.yyyy

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#1047]
Wenn man in den Einstellungen ein Pattern mit vollausgeschriebenen Monat einstellt, wird der Großteil des Datums in Datumsfeld abgeschnitten.

Einstellungen für das DatePattern:

<img width="698" alt="Bildschirmfoto 2021-12-03 um 09 08 16" src="https://user-images.githubusercontent.com/61147549/144567721-92873a92-1c1f-4f9f-a516-45b65fc5474f.png">

Ansicht im Detail:

<img width="702" alt="Bildschirmfoto 2021-12-03 um 09 07 19" src="https://user-images.githubusercontent.com/61147549/144567601-87364277-01de-47c6-848e-e04cacb421bc.png">

**Comment by janiak-minova** [comment]
Ich finde wir sollten die Felder breit genug machen damit das Datum auch in diesem Format komplett reinpasst.

**Comment by Bauer-David** [comment]
Wir haben die Breite des Datumsfelds an die der Lookups angepasst, dass es einheitlich ist.

Ansicht Detail mit der neuen Breite.

<img width="697" alt="Bildschirmfoto 2021-12-03 um 09 23 38" src="https://user-images.githubusercontent.com/61147549/144569643-ec0a2dc3-0122-4ec5-8d85-219bcae416ba.png">

**Comment by CE7** [comment]
Ich muss erlicherweise sagen, dass das Datumsfeld etwas verloren aussieht in der Maske wenn es so groß ist?

**Comment by Bauer-David** [comment]
Wir haben uns mit Christopher auf folgende maximale Länge geeinigt:

Als Pattern wird maximal dd.MMM.yyyy erlaubt. Beispiel Ansicht im Detail:

<img width="692" alt="Bildschirmfoto 2021-12-03 um 11 01 51" src="https://user-images.githubusercontent.com/61147549/144585171-0ecccb32-b9e0-4cae-bdb5-dd78b111a68a.png">

Ansicht mit Pattern dd.MM.yyyy:

<img width="696" alt="Bildschirmfoto 2021-12-03 um 11 01 05" src="https://user-images.githubusercontent.com/61147549/144585298-4c89bb06-9a36-4c9a-8810-9832bf3db160.png">

Mit dieser maximal Länge erlauben wir noch die Abkürzungen für die Monate. Alles was länger wäre, wird nicht unterstützt.
