### ISSUE TITLE
Anzahl geladener Einträge im Index begrenzen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1062]
Wenn mehr als 1.000 Einträge im Index geladen werden würde, soll es die Möglichkeit geben, nur einen Bruchteil von diesen in den Index zu laden. 

Das Laden des Index wird wie folgt ablaufen:

- [x] Anfrage ans CAS: Die ersten 1.000 Datensätze laden
- [x] Wenn mehr als 1.000: Dialog zum Setzten eines Limits
- [x] Anfrage ans CAS: Gewünschte Anzahl an Datensätzen laden; wenn weniger als 1.000 nur die gewünschte Anzahl anzeigen
- [x] Einstellung: Standard Limit ändern
- [x] Zum Nachladen Paging nutzen

**Comment by janiak-minova** [comment]
<img width="558" alt="Bildschirmfoto 2022-01-12 um 14 30 17" src="https://user-images.githubusercontent.com/77741125/149149612-9ae4b823-247c-4edf-9714-a59cef33da87.png">

**Comment by splitcells** [comment]
@janiak-minova @ingraban Auf der Server-Seite her,
wollen wir alles diesbezüglich über Paging haben.
Wenn man also nur die ersten 1000 Datensätze anfragen würde,
wäre dies immer (implizit) die erste Page.

Wenn man jetzt noch einen next und previous Knopf hätte,
könnte man so ein Pop-Up vermeiden.

**Comment by janiak-minova** [comment]
Besprechung mit SAW: Es gibt weiterhin den Dialog. Wenn mehr als 1.000 Datensätze angefragt werden, werden diese stückweise über Paging nachgeladen.
