### ISSUE TITLE
Double-Felder unter Windows lassen sich nicht richtig bearbeiten

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1084]
Zum Nachstellen:

1. Mit Tab in ein Double-Feld in dem bereits eine Zahl steht -> der gesamte Text ist markiert
<img width="156" alt="Bildschirmfoto 2021-12-16 um 15 50 03" src="https://user-images.githubusercontent.com/77741125/146393799-aa69aae9-fec7-4a03-99c4-bea960b0d838.png">

2. Tippen von "123" -> nur die 1 wird übernommen, alle weiteren Eingaben werden ignoriert
<img width="157" alt="Bildschirmfoto 2021-12-16 um 15 50 15" src="https://user-images.githubusercontent.com/77741125/146393857-b5e59bad-b1a8-4a39-ab28-ad62ee58df4b.png">

Man muss mit Maus/Pfeiltasten vor das Komma navigieren, damit die Eingabe ordentlich funktioniert.
Unter Mac tritt das Problem nicht auf.

**Comment by wis36** [comment]
Ich habe ein problematisches Verhalten, das hier dazu passt und das vielleicht auch nur unter Windows auftritt.

1. Ich klicke mit der Maus in ein Double-Feld. Caret steht ganz am Anfang, nichts ist markiert.
![grafik](https://user-images.githubusercontent.com/20420949/146505170-a012a433-7bb4-492e-8cb0-e69e496e3abd.png)

2. Ich drücke "Entf" um die Zahlen zu entfernen. (Da es mehrere Zeichen sind, drücke ich mehrmals) Beim ersten Entf rutscht die Position nur eins weiter. Beim zweiten Entf wird das Komma gelöscht und ich erhalte eine größere Zahl als vorher
![grafik](https://user-images.githubusercontent.com/20420949/146505584-93981364-9c91-4698-a632-bbb5592df342.png)

Bei Verwendung von TAB tritt es nicht auf, da hier automatisch der komplette Text markiert wird.

**Comment by DvonHolten** [comment]
dazu noch ein Hinweis:
wenn ihr euch mit Tausenderpunkten und Kommas beschäftigt - immer an die Localization denken.
Es gibt Länder, die haben Komma statt Tausenderpunkten und Punkt statt Komma, andere haben Hochkomma oder Leerzeichen als Tausendertrennzeichen... 
Und dann ist da noch das Vorzeichen...
