### ISSUE TITLE
Shift-Tab springt ins falsche Grid-Feld

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1103]
Mit folgenden Einstellungen sprint Shift-Tab ins falsche Grid Feld:
<img width="588" alt="Bildschirmfoto 2022-01-10 um 09 58 11" src="https://user-images.githubusercontent.com/77741125/148740066-c4fa6941-2650-4d27-ba9c-aac41ee8a518.png">

Bei Shift-Tab mit folgender Ausgangsstellung wird erwartet, dass in Zeile 2 Spalte Mwst. gesprungen wird. 
<img width="567" alt="Bildschirmfoto 2022-01-10 um 09 59 59" src="https://user-images.githubusercontent.com/77741125/148740263-f00f909a-fd0b-487c-9dec-c1373d9c2597.png">

Tatsächlich landet man aber in Zeile 1, Spalte "Menge".
<img width="561" alt="Bildschirmfoto 2022-01-10 um 10 00 28" src="https://user-images.githubusercontent.com/77741125/148740332-baa58035-865d-4e8b-967b-0a555e1eb7c2.png">

**Comment by Bauer-David** [comment]
Wird nun zusammengefasst in dem Issue #1144
