### ISSUE TITLE
Matchcodes bzw. Felder mit key-type="user" nur modifizierbar, solang noch nicht gespeichert wurde

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1118]
Wenn ein Feld mit dem Tag `key-type="user"` versehen ist, darf es nur bearbeitet werden, solange noch nicht zum ersten mal gespeichert wurde. Danach muss es `read-only` sein.

Frage:
In früheren Versionen waren diese Felder immer modifizierbar, solange der SuperUser-Modus eingeschaltet war. Diesen gibt es aber in Version 12 nicht. Soll es stattdessen eine Einstellung geben? Diese könnte aber aktuell von jedem Nutzer aktiviert werden (das wiederum könnte mit #885 gelöst werden).

**Comment by wis36** [comment]
Ich fände es sinnvoller, das über die Berechtigungen zu machen, die man Nutzern und Gruppen geben kann.

**Comment by ingraban** [comment]
In der neuen Version benötigen wir das erst einmal nicht.

Der SuperUser-Modus wird zur Zeit auch bei MINOVA missbraucht!! Die Anwender nutzen diesen Modus um Rechnungen zurückzusetzen, die sie nicht zuvor geprüft haben.
Das Umbenennen von Stammdaten ist besonders gefährlich, weil niemand mehr die Daten nachvollziehen kann.

Wenn man die Stammdaten umbenennen können soll, benötigen wir dazu eine eigene Funktion, die 
1. Die Änderung nachvollziehbar in der Datenbank loggt,
2. Über ein eigenes Recht gesichert wird,

Die Funktion [Rechnung zurücksetzen] ist auch eine Super-User-Funktion. Auch diese benötigt ein eigenes Recht und muss geloggt werden.
Die Erfahrung zeigt, dass Anwender nachlässiger werden, wenn sie solche Funktionen haben. Unser System wird durch die nachlässige Anwendung solcher Funktionen aber angreifbarer. So ein Verhalten entspricht nicht GAP (General Accounting Prozedures). 

Da wir jetzt ja auch die E-Mail direkt versenden, hat Nicole schon gefragt, ob man das nicht gesondert machen kann, damit sie die Rechnung vorher noch einmal prüfen kann. Ich frage mich, was mit anderen Verarbeitungsschritten passiert
- Übertragung an die FiBu
- Übertragung an Quicken
- ...

Dafür ist doch der Knopf verarbeiten da.
