### ISSUE TITLE
Connection-String bei dem ersten Starten vorbelegen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1124]
Oiltanking fragt an, ob es eine Möglichkeit gibt, beim ersten Start der Anwendung den Connection String schon über eine Konfigurationsdatei vorzubelegen, damit der User das nicht eintippen muss.

Ich finde das schwierig, weil die Datei dann ja schon in der ausgelieferten Anwendung enthalten sein müsste. Die Anwendung wäre dann von Kunde zu Kunde unterschiedlich.

**Comment by wis36** [comment]
Fände ich auch schwierig.

Bei dem Thema fiel mir ein, dass sich manche Clients ihren Server im lokalen Netzwerk selbst suchen. Ich weiß nicht, ob die dann einen Portscan oder etwas effizienteres machen? Vielleicht könnte man das auch übers AD des Kundennetzwerks hinterlegen?

**Comment by ingraban** [comment]
Wenn die Oiltanking Windows verwendet und sich in einem Active Directory bewegt, kann sie aber bestimmte Daten auf die Clients verteilen. Sie könnte dann auch eine Datei mit dem Connection-String und weiteren Protestes im Ordner USER_HOME\.minova\ einstellen. Solange wir dort gar kein Profil finden, könnten wir prüfen, ob die Datei vorhanden ist und dann aus dieser die Properties laden.

**Comment by janiak-minova** [comment]
Wie SAW vorgeschlagen hat, wird mit #1125 versucht, eine Datei `<BenutzerOrdner>/.minwfc/settings.properties` einzulesen. Wenn dort die property `defaultConnectionString` definiert ist, wird diese als Connection String in die Login-Maske eingetragen,  solange es keine Profile gibt.


```
defaultConnectionString=https://stunden.minova.com:8084
```

<img width="524" alt="Bildschirmfoto 2022-01-21 um 11 52 08" src="https://user-images.githubusercontent.com/77741125/150514761-a6cebc71-79d6-44f2-a2da-cbcbe2a58610.png">


Wenn wir noch weiter Properties definieren können wir sie [hier](https://github.com/minova-afis/aero.minova.rcp/blob/master/SettingsProperties.adoc) dokumentieren.
