### ISSUE TITLE
DateTime-Feld unter Windows zu lang

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1128]
Ein Datetimefeld in Spalte 3-4 ist unter Windows zu lang und wird rechts abgeschnitten:

<img width="564" alt="Bildschirmfoto 2022-01-25 um 14 05 02" src="https://user-images.githubusercontent.com/77741125/150982157-7de45ea5-528d-4acf-8af9-bb9eaf49954e.png">

**Comment by Bauer-David** [comment]
Es liegt daran, dass wir die Abkürzungen von den Monaten zulassen. Würde wir nur Zahlen zu lassen, würde sich das Problem lösen lassen

**Comment by janiak-minova** [comment]
Ich meine wirklich das Feld in der UI, das ist rechts visuell abgeschnitten. Ob der Inhalt abgeschnitten wird ist ein separates Problem.

**Comment by Bauer-David** [comment]
Die visuelle Länge wird durch die von uns bestimmte maximal Länge festgestellt, weshalb wir mit den Abkürzungen eine zu große maximal Länge haben und es die Länge des Parts überschreitet.

**Comment by janiak-minova** [comment]
Mit den neuen Layout nicht mehr.

Auch vorher waren DateTime-Felder auf die Länge von Textfeldern gesetzt.

**Comment by Bauer-David** [comment]
Achso ok, dann vergiss es ^^
