### ISSUE TITLE
Verhalten von "Entfernen" in Doublefeldern nach dem Komma

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1132]
Ausgangslage: Cursor steht direkt hinter dem Komma.
<img width="174" alt="Bildschirmfoto 2022-01-26 um 08 00 39" src="https://user-images.githubusercontent.com/77741125/151117603-0effef61-6226-49ff-a77e-489dd0b000bf.png">

Nach Betätigen von "Entfernen": die 3 wurde entfernt, die 4 ist aufgerückt, der Cursor steht nach der 4. Betätigt man nun erneut "Entfernen" rückt der Cursor hinter die 0. Die 4 kann nicht entfernt werden, ohne eine andere Taste zu nutzen.
<img width="179" alt="Bildschirmfoto 2022-01-26 um 08 00 50" src="https://user-images.githubusercontent.com/77741125/151117634-d50bc8da-a4b0-4de7-a5f1-8814918cdaec.png">

Ist das Verhalten so gewünscht?

**Comment by ingraban** [comment]
Nein - siehe README.adoc (@Bauer-David das müsstest Du noch wissen)

Vorher | Eingabe | Nachher
|----|----|----|
12,<C>34 | <BACKSPACE> | 12<C>,34
12,<C>34 | <DEL> | 12,<C>40
