### ISSUE TITLE
Tab bestätigt unter Windows nicht die Auswahl im Lookup

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#1141]
Unter Windows kann die Auswahl in der Vorschlagsliste eines Lookups nicht mit Tab bestätigt werden. Betätigt man Tab in der Vorschlagsliste unter Windows passiert nichts. Es wird nichts ausgewählt und die Vorschlagsliste bleibt offen. Es wird nicht weiter gesprungen.

**Comment by wis36** [comment]
Bei mir funktioniert das normalerweise. (12.0.27)
Nur wenn die Vorschlagliste den Fokus hat, funktioniert es nicht mehr.

**Comment by Bauer-David** [comment]
Hab die Beschreibung aktualisiert. Habe die Vorschlagsliste gemeint, aber habe Lookup geschrieben.

**Comment by Bauer-David** [comment]
Der Fehler wurde behoben durch den Merge des neusten Master auf den Branch #684
