### ISSUE TITLE
Spalten im Index ein-/ausblenden

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1146]
Die Oiltanking möchte gerne, dass der Index des Kunden und des Warenempfängers um die Kundennummer erweitert wird. Dabei hat Kathrin erwähnt, dass es schon länger eine Möglichkeit geben soll, einzelne Spalten im Index ein- und auszublenden. Bei der Kundennummer ergibt es ja z.B. nur Sinn diese anzuzeigen, wenn auch die entsprechende OP genutzt wird. 

Wir möchten nun ein Konzept erarbeiten, wie definiert wird, welche Spalten im Index ein- bzw. ausgeblendet werden.

Gerne können wir dafür auch einen Termin vereinbaren.

**Comment by ingraban** [comment]
Gibt es denn schon eine Idee

**Comment by janiak-minova** [comment]
Mein Vorschlag ist eine Umsetzung über die .xbs. Wir können die Einträge für die einzelnen Masken um eine weitere Node `Index` erweitern, in der definiert wird, ob eine Spalte sichtbar sein soll. Ist für eine Spalte kein Eintrag vorhanden wird die Spalte angezeigt.


In folgendem Beispiel sind die `Kundennummer`-Spalten in den Masken Journal und Kunde eingeblendet. Die Spalten `Letzter Benutzer` und `Letzte Änderung` in Maske Kunde sind ausgeblendet.
````
<node name="Journal.xml">
	<map />
	<node name=„Index“>
		<map>
			<entry key="OrderReceiverUserCode" value="true" />
		</map>
	</node>
</node>
<node name="OrderReceiver.xml">
	<map />
	<node name=„Index“>
		<map>
			<entry key="UserCode" value="true" />
			<entry key="LastUser" value="false" />
			<entry key="LastDate" value="false" />
		</map>
	</node>
	<node name="OptionPages">
		<map />
		<node name="ReceivableAccounts.op.xml">
			<map>
				<entry key="OrderReceiverKey" value="KeyLong" />
			</map>
		</node>
		<node name="OrderReceiverUserCode.op.xml">
			<map>
				<entry key="OrderReceiverKey" value="KeyLong" />
			</map>
		</node>
	</node>
</node>
````

**Comment by janiak-minova** [comment]
Zusätzlich könnten wir die Möglichkeit geben, Spalten über das UI ein- und auszublenden.

<img width="426" alt="Bildschirmfoto 2022-02-07 um 12 01 56" src="https://user-images.githubusercontent.com/77741125/152776085-da142897-32d0-44fb-9d21-4daa67a0fe90.png">

**Comment by MokMinova** [comment]
XBS finde ich ok, da muss man nur einmal nachsehen wie die Index-Spalte in den anderen Masken heißt und es in der entsprechenden OP im Setup eintragen. Und falls gewünscht kann man es im Setup des Kunden überschreiben.

Die UI-Änderung würde ich auf jeden Fall machen. Da kann sich jeder Benutzer raussuchen was er gerne möchte...

**Comment by janiak-minova** [comment]
Aktuell werden die XBS eh noch per Hand geschrieben, das müsste man also extra eintragen.

**Comment by ingraban** [comment]
Wenn ich das richtig verstehe, haben wir folgende Idee

### Spalten im Index

Im Index werden alle Spalten eingetragen, die es geben kann. Dies bedeutet auch, dass man für neue Spalten einer OptionPage auch eine neue Version der Hauptmaske erstellen muss.

### Ein- / Ausblenden über XBS-Einträge

Man kann die einzelnen Spalten über die Konfiguration in der XBS ein- und ausblenden. Hierbei entstehen für mich folgende Fragen.

1. Müssen alle OptionPage Felder in der Hauptmaske ausgeblendet werden?
2. Müssen die OptionPages diese dann einblenden und überschreiben diese dann die Werte?
3. Sollten wir dann auch vorsehen, dass die Reihenfolge der Spalten in der XBS definiert werden kann?

### Ein- / Ausblenden über das UI

In fände es super, wenn man Spalten über das UI aus- und einblenden kann. Dabei sollten wir auch die Möglichkeit bieten, dies mit einer Ansicht (Sortierreihenfolge, Suchkriterien...) zu verbinden. Dadurch könnte der Anwender schöne Reports generieren. 

Folgende Fragen:

1. Wenn wir dann Spalten ausblenden, sollten wir diese dann auch nicht mehr vom Server laden?
2. Wenn wir Spalten wieder einblenden, müssen wir das Drucken unterbinden, bis der Anwender die Daten neu geladen hat, damit alle Spalten mit den Werten aus der Datenbank übereinstimmen?

**Comment by janiak-minova** [comment]
**Ergebnis der Besprechung am 08.02.22**

Das Ein- und Ausblenden wird NICHT über die XBS geregelt. 
Stattdessen soll es über das UI möglich sein.
- Neuer Knopf im Index, der einen Dialog mit Liste aller im Index definierten Spalten öffnet (solange diese einen `text` haben)
- Jede Spalte kann über eine Checkbox ein- oder ausgeblendet werden
- Die Auswahl betrifft auch die Suche
- Ausgeblendete Spalten werden bei Anfragen ans CAS nicht berücksichtigt (außer sie sind key-Spalte)
- Die Auswahl wird persistiert und kann in Suchkriterien gespeichert werden

Masken sollten überarbeitet werden, sodass Spalten, die nur über OPs gefüllt werden können, per Default ausgeblendet sind.

Um Kunden zu ermöglichen, Ansichten für ihre Nutzer zu definieren, müssen wir #386 umsetzen.

**Comment by CE7** [comment]
Ich habe das Icon hinzugefügt. Bitte nochmal aktualisieren

**Comment by ingraban** [comment]
Wie heißte das Icon? und wo finde ich es?

https://github.com/minova-afis/aero.minova.rcp/tree/master/bundles/aero.minova.rcp.images

**Comment by janiak-minova** [comment]
Ist auf Branch jal-#1146-Indexspalten_ein_und_ausblenden.

[Image](https://github.com/minova-afis/aero.minova.rcp/tree/jal-%231146-Indexspalten_ein_und_ausblenden/bundles/aero.minova.rcp.images/images/ExpandShrinkIndex.Command)
