### ISSUE TITLE
loginDefaultWorkspace liefert immer null

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#1152]
Beim WFC-Start wird geprüft, ob ein Default Workspace vorhanden ist.

Dieser soll mit
`loginDefaultWorkspace(workspaceLocation, workspaceDialog);`
geladen werden.

Das wird aber aktuell nur gemacht, wenn
`if (!Platform.getInstanceLocation().isSet())`

Wenn ich übers Eclipse starte, ist die InstanceLocation aber set. Also bekomme ich immer `null`.
Ich weiß nicht, was beim Start der exe passieren würde.

Wahrscheinlich müsste die schließende Klammer von dem if weiter hoch. Damit funktioniert es bei mir auch wieder.

**Comment by wis36** [comment]
Hm, jetzt erinnere ich mich, dass man die Location löschen musste.

Ich habe es gelöscht, jetzt kann ich das WFC starten.

Trotzdem sollte etwas definiertes passieren, wenn man eine Workspace Location angibt.

An dieser Stelle wird ja sowieso vieles geprüft und ausprobiert. Der Wert wird sogar programmatisch gesetzt. Dann könnte man auch berücksichtigen, dass er vorher schon vorhanden war (aus Debug config oder config.ini)?

**Comment by janiak-minova** [comment]
Wir wollen ja einen eigenen Workspace pro Profil. Wenn der Workspace schon in der Debug config gegeben ist wird dieser für jedes Profil genutzt, das führt nur zu Verwirrung.

Ich kann schauen, dass der Code soweit angepasst wird, das die in der Debug config gesetzte Location komplett ignoriert wird.

**Comment by janiak-minova** [comment]
Die Location zu ignorieren, ist leider nicht möglich. Ist sie einmal gesetzt, kann sie nie wieder geändert werden.


Stattdessen wird jetzt der Start der Anwendung komplett abgebrochen:
<img width="684" alt="Bildschirmfoto 2023-04-13 um 14 36 21" src="https://user-images.githubusercontent.com/77741125/231763344-307d5362-3d04-4c70-b935-6d30550fbd7f.png">

Damit ist klar, dass diese Location entfernt werden muss.
