### ISSUE TITLE
Aktualisierung der Lookup Listen zu spät

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#1156]
Wenn ein der Stundenerfassung ein Ticket zu einem Kunden eingetragen wird, werden im Hintergrund zum Beispiel die möglichen Aufwände geladen. 

Wenn man aber danach alle Felder "löscht" und manuell einen anderen Kunden Stunden erfassen möchte werden die zugehörigen Auswahlmöglichkeiten des vorherigen Kunden angezeigt. 
Vorher wurde zum Beispiel das Ticket: #55565 geladen!

Nach dem Löschen, bei dem Versuch einen Aufwand auszuwählen stehen noch die "alten" drin!
<img width="594" alt="Bildschirmfoto 2022-02-11 um 10 04 34" src="https://user-images.githubusercontent.com/20420898/153567500-ef065eb3-8c5e-4b95-9a62-edbd55b93b30.png">

Beim 2. Öffnen ist es dann korrekt. 
<img width="612" alt="Bildschirmfoto 2022-02-11 um 10 04 45" src="https://user-images.githubusercontent.com/20420898/153567509-b1242870-d7c9-4ae8-84c3-5c486eb81c1c.png">

**Comment by janiak-minova** [comment]
Da wir die aktuelle Version der Anwendung nicht mit der Stundenerfassung zusammen verwenden können müssen wir erst auf ein Update warten.
