### ISSUE TITLE
Komplettes Löschen von Werten in Nummer-Feldern ermöglichen?

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1168]
Aktuell kann der Inhalt eines Nummernfelds nicht wieder komplett entfernt werden, wenn einmal etwas in das Feld geschrieben wurde. Markiert man den kompletten Inhalt und betätigt Entfernen wird das Feld mit 0 gefüllt. Allerdings wäre es denkbar, dass eine Eingabe von `null` benötigt wird. 

Soll das komplette Entfernen einer Zahl ermöglicht werden?

**Comment by ingraban** [comment]
Grundsätzlich muss es auch möglich sein, wieder einen leeren Wert (null) zu speichern, wenn das Feld nicht als `required` definiert wurde.
