### ISSUE TITLE
Falsche Fehlermeldung: "IOException too many authentication attempts"

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.rcp#1205]
WFC-Version: 12.0.27.202110011314, BuildDate: 21-12-01T12:42:47 Java Runtime: 11.0.2+9

<img width="853" alt="Bildschirmfoto 2022-05-04 um 10 27 26" src="https://user-images.githubusercontent.com/95353437/166646577-dd9fbcab-6d09-4551-94ea-d6fbf27ca1aa.png">

Auf der Login-Maske der Zeiterfassung erscheint die Fehlermeldung: `IOExeption too many authentication attempts, Limit: 3 User or Password incorrect?`

<img width="598" alt="Bildschirmfoto 2022-05-04 um 10 26 27" src="https://user-images.githubusercontent.com/95353437/166646606-cbdce0ec-c30e-4d70-ba96-da3bd104539c.png">

Ursache der Fehlermeldung ist der überflüssige Slash am Ende der URL im Feld `Connection String`. Die Benutzer/Passwort-Kombination ist völlig korrekt.

**Comment by janiak-minova** [comment]
Siehe #1207, der überflüssige Slash sollte komplett ignoriert werden.
