### ISSUE TITLE
Falsches Beispiel ?

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1228]
der markierte Code befindet sich in aero.minova.rcp.rcp.fields.FieldUtils.java .
Es ist unklar, ob bewusst ein Fehler getriggert werden soll (was in einem static initializer problematisch ist) oder ob diese Zeit stillschweigend angenommen wird.

![grafik](https://user-images.githubusercontent.com/41451972/169689137-0f111717-29a4-4a2a-a635-b73990546447.png)

**Comment by janiak-minova** [comment]
Der static initializer wird nur genutzt, um die Länge der Felder zu bestimmen. Dafür wird eben der längste erlaubte Text eingegeben und dann gespeichert, wie breit das Feld dafür sein muss. Der Text muss also keinem validen Datumsformat entsprechen. 

Allerdings wird dieser Wert eh nicht mehr genutzt, ich habe ihn mit #1239 entfernt.
