### ISSUE TITLE
Neues UI-Element RadioBox

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.rcp#1235]
ALS: Kunde
MÖCHTE ICH: Eine Auswahl unter mehreren Möglichkeiten treffen (RadioBox statt Lookup)
SO DASS: Ich platzsparend die Auswahlmöglichkeiten ähnlich einem ausgedrucktem Dokument sehen kann.

**Technische Details:**
- Es sollte eine der angebotenen Möglichkeiten auch bereits vorselektierbar sein (Default-Wert)
- Wird für `Checkliste automatisch für Eingaben generieren` https://github.com/minova-afis/com.minova.sam.scharr/issues/34 benötigt.

**Comment by scholz-afis** [comment]
@CE7 Wie besprochen, Issue angelegt.

**Comment by janiak-minova** [comment]
Duplikat von #1242
