### ISSUE TITLE
Updates führen zu inkonsitenten Workspaces

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#125]
Wir haben festgestellt, dass die Anwendung nicht sauber funktioniert, wenn man ein neues Plugin wie zum Beispiel aero.minova.rcp.images hinzufügt und sie dann startet. 

Die Bilder wurden erst nachdem wir einen neuen Workspace angelegt haben angezeigt.

**Comment by janiak-minova** [comment]
Duplikat #519
