### ISSUE TITLE
Mehrere Helper pro Maske

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1271]
Ist es möglich, dass eine Maske mehrere Helper hat?

In der Maske kann z.B. ein Helper direkt im `form` Tag definiert werden, einer in einem Grid, sowie zusätzlich in den OPs.

Aktuell unterstützt die Anwendung nur einen Helper pro Maske.

**Comment by wis36** [comment]
Aktuell kann jede Maske nur einen Helper haben. Grids und OPs zählen in der Hinsicht allerdings auch als Maske. Im TTA kommt das öfters vor. Teilweise melden sich die OP-Helper dann auch beim Helper der Hauptmaske an, damit dieser die untergeordneten Helper ansteuern / abfragen kann.

**Comment by janiak-minova** [comment]
Ok, dann würde ich als ersten Schritt umsetzten, dass pro Hauptmaske, Grid und OP jeweils ein Helper registriert werden kann.

> Teilweise melden sich die OP-Helper dann auch beim Helper der Hauptmaske an, damit dieser die untergeordneten Helper ansteuern / abfragen kann.

Wie das funktionieren soll kann ich mir gerade noch nicht vorstellen, das würde ich hinten anstellen bis wir ein konkretes Beispiel haben, in dem das benötigt wird.
