### ISSUE TITLE
WFC-Cache deaktivierbar machen.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#1299]
Für das CAS habe ich eine Method dokumentiert, wie man Masken mit CAS und WFC live editieren könnte: https://github.com/minova-afis/aero.minova.cas/blob/master/service/doc/adoc/installation.dev.adoc#snapshot-docker-image-lokal-bauen-ausf%C3%BChren-und-masken-live-editieren

Dazu nimmt man ein Kundenprojekt, baut es und startet CAS mit einen Dockerbefehl,
welcher einige Unterordner vom target direkt einbindet.
Dadurch kann man die Dateien im target editieren und das CAS, kann diese sofort bereitstellen.
Dazu muss man aber zur Zeit im WFC den Cache löschen und neustarten, wenn man etwas editiert will,
was recht umständlich.

Es wäre schön, wenn das WFC seinen lokalen Cache mit einer Option im Experten Modus ignorieren könnte,
sodass man die Maske nur schliessen und öffnen muss, um die neuste Version zu haben.

**Comment by janiak-minova** [comment]
Mit #1303 umgesetzt.

Die Einstellung ist im Tab "Erweitert" zu finden. Damit reicht es, eine Maske zu schließen und wieder zu öffnen um die entsprechende .xml Datei erneut vom CAS zu laden. Der Hash wird komplett ignoriert.


Für Änderungen an .mdi, .xbs, Übersetzungen und Bildern muss die Anwendung allerdings dennoch neu gestartet werden, da diese Dateien nur beim Start heruntergeladen werden.

Die Einstellung verlangsamt die Anwendung, da öfter Dateien heruntergeladen werden.

<img width="1015" alt="Bildschirmfoto 2022-07-12 um 14 01 08" src="https://user-images.githubusercontent.com/77741125/178672663-f9252992-8eef-470a-9bf5-7f995a878c0a.png">

<img width="615" alt="Bildschirmfoto 2022-07-13 um 09 11 33" src="https://user-images.githubusercontent.com/77741125/178673025-089b7c49-173e-4e69-8b86-f5076de82341.png">
