### ISSUE TITLE
handleDetailAction(): Informationen über gelöschte Zeilen fehlt

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.rcp#1314]
ALS: Entwickler
WILL ICH: wissen, welche Zeilen der Benutzer aus dem Grid gelöscht hat
SO DASS: Ich in der `BEFORESAVE` Methode entsprechende Aktionen durchführen kann.

***Technische Details:***
* Im aktuellen Fall geht es um das Löschen Dateien von einem S3-Service, die in einer Zeile der Tabelle referenziert wurden. Die Zeile wurde aus der Tabelle gelöscht und in der `BEFORESAVE` Methode nicht mehr verfügbar.

```
	public void handleDetailAction(ActionCode actionCode) {

		switch (actionCode) {
		case BEFORESAVE:
```

**Comment by janiak-minova** [comment]
Um an die zu Löschenden Zeilen zu kommen kann folgender Code verwendet werden:

````
public void handleDetailAction(ActionCode actionCode) {

		MGrid grid = mDetail.getGrid("GridName");
		
		switch (code) {

		case BEFORESAVE: // Von Nutzer:in gelöschte Zeilen herausfinden
			List<Row> rowsToDelete = ((GridAccessor) grid.getGridAccessor()).getSectionGrid().getRowsToDelete();
			// TODO: Delete
			break;
		case BEFOREDEL: // Wenn der gesamte Datensatz gelöscht wird sollten auch alle Zeilen entfernt werden
			rowsToDelete = grid.getDataTable().getRows();
			// TODO
			break;
		}
}
````


Der Umweg über die `GridAccessor` ist etwas unhandlich, ich werde das `MGrid` erweitern, sodass die Zeilen direkt erreichbar sind.
