### ISSUE TITLE
RCP: Anzeige von Code-Coverage in SonarQube

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.rcp#1341]
ALS: Entwickler
MÖCHTE ICH: Das SonarQube die Code-Coverage vom RCP Projekt anzeigt
SO DASS: ich die Tendenz der Testabdeckung auf einem Blick verifizieren kann.

**Technische Details:**
* Es handelt sich um ein Multi-Modul basierend auf Mavens `pom.xml`
* Die Sub-Module hängen überraschenderweise nicht von der Parent-POM im Root-Verzeichnis ab
* Außerdem findet mit `Tycho` noch ein weiteres Build-Tool Anwendung, dass on-the-fly POMs erstellt bzw. manipuliert.

**Comment by scholz-afis** [comment]
Nachdem ich mit Änderungen im RCP Projekt auf keinen grünen Zweig gekommen bin, habe ich mich entschlossen erst ein simples Projekt zu erstellen und sukzessiv Richtung RCP umzubauen:

**Links:**
* https://github.com/minova-afis/aero.minova.maven.sample.multimodule
* https://sonarqube.minova.com/dashboard?id=minova-afis_aero.minova.maven.sample.multimodule

**Comment by scholz-afis** [comment]
Ich habe eine Unverträglichkeit zwischen JUnit4-, JUnit5-Tests und JaCoCo festgestellt:

Fall 1) Dependency `org.junit.jupiter:junit-jupiter-engine` ist vorhanden
* Junit4 Tests erscheinen **nicht** in der JaCoCo Coverage
* Junit5 Tests erscheinen in der JaCoCo Coverage

Fall 2) Dependency `org.junit.jupiter:junit-jupiter-engine` ist **nicht** vorhanden
* Junit4 Tests erscheinen in der JaCoCo Coverage
* Junit5 Tests können wegen fehlender `import` Möglichkeit nicht kompiliert werden.

**Comment by janiak-minova** [comment]
> Fall 1) Dependency `org.junit.jupiter:junit-jupiter-engine` ist vorhanden (das Profil `java-maven-junit-5` in `maven.root` ist per default aktiv):
> 
> * Junit4 Tests erscheinen **nicht** in der JaCoCo Coverage. Unabhängig davon, ob als Dependency `junit:junit` oder `org.junit.vintage:junit-vintage-engine` eingegeben wurde.
> * Junit5 Tests erscheinen in der JaCoCo Coverage


Ich denke mit diesem Fall können wir gut leben. JUnit4 wollen wir eh seit langem abschaffen #535, da kann ich mich dranmachen.

**Comment by scholz-afis** [comment]
`Tycho` ist schon sehr speziell. Nun habe ich ein diesbzgl.  Beispiel aus dem Jahre 2018 modernisiert und zur Coverage Ausgabe gebracht. Erste Feststellung: Sind `install` und `sonar:sonar` nicht im gleichem Aufruf, dann wird das nichts mit der Coverage. 

**Links:**
* https://github.com/minova-afis/aero.minova.tycho.sample.multimodule
* https://sonarqube.minova.com/dashboard?id=minova-afis_aero.minova.tycho.sample.multimodule

**Comment by scholz-afis** [comment]
* https://sonarqube.minova.com/dashboard?branch=scr_dependency_updates&id=minova-afis_aero.minova.rcp
![image](https://user-images.githubusercontent.com/95353437/216643188-718a022b-fdc2-41ff-b7fe-c735555592e6.png)

Cc: @Bauer-David

**Comment by janiak-minova** [comment]
Funktioniert mit master.
