### ISSUE TITLE
AsciiDoc Markup Durcheinander

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1344]
es gibt in diesem und anderen Projekten eine Reihe von Dateien mit .adoc - Erweiterung. 
Möglicherweise haben der GitHub-Browser-Editor oder ein Eclipse-Plugin die Finger im Spiel.
Ich schlage eine übergreifende Festlegung vor, welche Markierungen verwendet werden sollen.

Das AsciiDoc-Plugin von IntelliJ bemängelt verschiedene Markierungen:

vorher:
![grafik](https://user-images.githubusercontent.com/41451972/182639479-94abf96e-f87a-4e8b-9a3c-deb34e649fe1.png)

nachher:
![grafik](https://user-images.githubusercontent.com/41451972/182639741-f4b737d7-315a-4d77-8b84-9f470fa033b5.png)

Ausgabe für beide gleich:
![grafik](https://user-images.githubusercontent.com/41451972/182639077-a9375e47-e729-4839-8fcd-2e9b71d3d110.png)

**Comment by CE7** [comment]
So wie es sich für mich darstellt, ist es einmal in MarkDown und einmal in AsciiDoc geschrieben. 

MarkDown: 
* Überschrift mit Präfix ###
AsciiDoc
* Überschrift mit Präfix ===

**Comment by janiak-minova** [comment]
Changelog zu Markdown Datei umgewandelt, damit Abschnitte weiterhin direkt in Releasenotes kopiert werden können.
