### ISSUE TITLE
Fehlende Verwerfen Nachricht beim Selektieren des selben Datensatzes

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#1354]
**Beschreibung**
Wird im Index der selbe Datensatz selektiert, der gerade editiert wird, werden ohne nachzufragen alle Änderungen verworfen.

**Zum Nachstellen**
1. Einen Datensatz im Index selektieren
2. Im Detailbereich Änderungen vornehmen
3. Ohne zu speichern wieder den selben Datensatz im Index selektieren

**Screenshots**
1. Datensatz selektiert
![Bildschirmfoto 2022-08-09 um 10 55 22](https://user-images.githubusercontent.com/61147549/183608890-9f607e3c-140d-4f5b-b308-929c13b4c6f3.png)

2. Änderungen (rot umrandet) vornehmen
![Bildschirmfoto 2022-08-09 um 10 55 42](https://user-images.githubusercontent.com/61147549/183610115-d180a430-755c-44fb-b2af-94ae5951b245.png)

3. Datensatz im Index nochmal selektiert. Änderungen ohne Warnung verworfen.
![Bildschirmfoto 2022-08-09 um 10 55 54](https://user-images.githubusercontent.com/61147549/183610339-2f440ec3-cb2a-4093-a028-3063f132564e.png)

**Comment by janiak-minova** [comment]
<img width="697" alt="Bildschirmfoto 2022-08-09 um 11 08 26" src="https://user-images.githubusercontent.com/77741125/183610701-989a35ac-35e4-4997-8c76-1071a829a15b.png">

Ist denn die entsprechende Einstellung gesetzt?

**Comment by Bauer-David** [comment]
Ich dachte ja, aber sie war tatsächlich nicht gesetzt. Ich schließe hiermit das Issue
