### ISSUE TITLE
Feste Werte in der xbs konfigurieren

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1357]
Es muss möglich sein, in der xbs feste Werte für Felder/Spalten zu konfigurieren.
Um feste Werte von Verweisen auf Felder in der Hauptmaske zu unterscheiden müssen sie entsprechend gekennzeichnet werden, z.B. mit einem "@".

Evtl. sollten auch die Verweise auf Felder der Hauptmaske überarbeitet werden, bei einer neuen Zeile im Grid sollte z.B. der entsprechende Wert sofort eingetragen werden.

**Comment by wis36** [comment]
Meinst du sowas wie static keys?
`<entry key="ReferenceTypeKey" value="4"/>`
In der XBS wird ein statischer Wert festgelegt, den das Feld in der Maske bekommt

**Comment by wis36** [comment]
oder sowas?
`<entry key="visible-when" value="Parent_ModeOfTransportTypeKey == 11"/>`
bisher hatten wir für Felder in der Hauptmaske "Parent_" vorangestellt

**Comment by janiak-minova** [comment]
> Meinst du sowas wie static keys?
> `<entry key="ReferenceTypeKey" value="4"/>`
> In der XBS wird ein statischer Wert festgelegt, den das Feld in der Maske bekommt

Ja, sowas in die Richtung. 
Ich möchte neben ints/Keys aber auch Strings und alle anderen Datentypen unterstützen, weshalb mMn eine Kennzeichnung nötig ist, ob es sich um einen festen Wert handelt, oder ein Feld aus der Hauptmaske. 

Auch in alten xbs wurde soweit ich weiß bei einem Verweis kein "Parent_" vor das Feld geschrieben, wenn der Wert direkt übernommen werden sollte.
`visible-when` Bedingungen sind wieder was anderes, das ist noch nicht umgesetzt.

Alte xbs:
```
<node name="TruckADR.op.xml">
  <map>
      <entry key="Key0" value="VehicleKey"/> <!-- erster Key aus Hauptmaske soll ich Feld VehicleKey eingetragen werden?? -->
      <entry key="ReferenceTypeKey" value="4"/> <!-- Ins Feld ReferenceTypeKey soll immer 4 eingetragen werden -->
  </map>
</node>
```     

Die alte Version finde ich etwas inkonsistent, einmal steht das Feld der OP im `key`, einmal im `value`.

Neue xbs:
```
<node name="TruckADR.op.xml">
  <map>
      <entry key="VehicleKey" value="KeyLong"/> <!-- Im Feld VehicleKey soll der Wert des Feldes KeyLong der Hauptmaske stehen -->
      <entry key="ReferenceTypeKey" value="@4"/> <!-- Ins Feld ReferenceTypeKey soll immer 4 eingetragen werden -->
  </map>
</node>
```

Der Teil `<entry key="VehicleKey" value="KeyLong"/>` ist so schon umgesetzt, `<entry key="ReferenceTypeKey" value="@4"/>` wird mit diesem Issue bearbeitet

**Comment by wis36** [comment]
> Alte xbs:
> 
> ```
> <node name="TruckADR.op.xml">
>   <map>
>       <entry key="Key0" value="VehicleKey"/> 
>       <entry key="ReferenceTypeKey" value="4"/> 
>   </map>
> </node>
> ```
> 
> Die alte Version finde ich etwas inkonsistent, einmal steht das Feld der OP im `key`, einmal im `value`.
Es sind auch 2 verschiedene Sachen.

1. erster Key aus Hauptmaske
 * wird nicht nur eingetragen, sondern darüber funktioniert die Verknüpfung zwischen Haupt- und OptionPage
 * der Name des Keys aus der Hauptmaske muss nicht bekannt sein, es funktioniert trotzdem - den Nutzen verstehe ich allerdings nicht
2. eintragen eines statischen Wertes (Datentyp egal)

Ich finde das neue Konzept tatsächlich besser 👍🏻

**Comment by janiak-minova** [comment]
Kommentare von SAW:
- Als Unterscheiden zwischen Feldnamen und statischem Wert ein `#` verwenden
- Bei einem Textfeld statischen Wert übersetzten, wenn am Anfang ein `@` enthalten ist: 
`<entry key="Description" value="#@Description"/>` -> `Description` übersetzen
- Für Datums-/Zeitfelder auch Eingaben von Shortcuts (z.B. `0`, `0101`, ...) erlauben

**Comment by janiak-minova** [comment]
Doku ist in der [Wiki](https://github.com/minova-afis/aero.minova.rcp/wiki/application.xbs) zu finden
