### ISSUE TITLE
Probleme mit Lookup zu param-String in gleicher Section

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1358]
Ist das Lookup, über welches das Param-String Felde gesteuert wird, im gleichen Abschnitt wie dieses, treten noch einige Probleme auf.

Beispiel: Param-String wird über Feld "Formular" gesteuert:

<p float="left">
 <img width="400" alt="Bildschirmfoto 2022-08-12 um 10 21 57" src="https://user-images.githubusercontent.com/77741125/184314750-8002fd5d-2bd7-40a5-88e8-c7ffb05954f1.png">
  <img width="400" alt="Bildschirmfoto 2022-08-12 um 10 23 15" src="https://user-images.githubusercontent.com/77741125/184314937-9e82828e-c1e8-4b2e-9217-04ece03d605d.png">
</p>
   

- [x] Nur ein Eintrag in Lookup -> Wert kann nicht entfernt werden, weil ein Lookup immer sofort den Wert einträgt, wenn nur einer zur Auswahl steht
- [x] Erster Wert in Lookup ist eingetragen -> Klick auf "Neu" -> ConcurrentModificationException
- [x] Wählen eines neuen Werts im Lookup über Enter -> SWTException: Widget is disposed

**Comment by CE7** [comment]
Wenn wir die Kombination aus Pflichtfeld und Lookup prüfen, dann würde sich nur ein Wert in das LookUp eintragen, wenn das Feld den Fokus bekommt und es ein Pflichtfeld ist. Ist dann nur eine Möglichkeit zur Eintragung vorhanden, wird es automatisch angezeigt. 

Wenn das Lookup wie in unserem Beispiel kein Pflichtfeld ist. Wird bei der Methode: focusGained() nicht automatisch der ein Wert eingetragen.

diese kleine Änderung halten ich für Sinnvoll und sehr schön: #geileLösung

Begründung: 
Wenn ein Datensatz angelegt wird, und dieser auch ein Lookup unausgefüllt lassen darf, wäre es ein Zusätzlicher Aufwand immer den einen möglichen Datensatz aus dem Lookup zu entfernen wenn man mit Tab durch alle Felder springt.
