### ISSUE TITLE
Screenshots mit der Anwendung erstellen

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#1364]
Wie im 11er Stand soll es wieder die Möglichkeit geben, dass man aus der Anwendung Screenshots von OptionPages erstellen kann. **Vorherige Funktionsweise:** 
1. Maske mit Optionpages öffnen
2. Anmeldung in der Konsole als "SuperUser"
3. mittels Drag&Drop die Section (OptionPage) bewegen
4. Bildschirmfoto mit individuellem Namen in einem Fenster speichern: 

Fenster nach dem Drag&Drop
<img width="925" alt="Bildschirmfoto 2022-08-17 um 15 02 12" src="https://user-images.githubusercontent.com/20420898/185140878-1246c7be-5382-48b5-84c5-31092833ecee.png">

Screenshot, der erstellt worden ist.
![Untitled](https://user-images.githubusercontent.com/20420898/185140909-0bccf3a6-3daa-43fa-9791-246f9ea4bc8b.png)

Dieser Screenshot hat immer die gleiche Größe und ist damit Ideal für Dokumentationen verwendbar.

**Comment by janiak-minova** [comment]
Anmerkungen SAW:

- [ ] Möglichkeit, vom ganzen Part Screenshot zu erstellen
- [ ] Namensschema der Dateien: `<Name der Maske>_<ID der Section/Part/Toolbar>.png` (z.B. `Truck_Head.png`, `Truck_DetailTB.png`, `Truck_Index.png`)

Außerdem:

- [ ] Exeption, wenn Anwendung nicht ordentlich im Fokus ist abfangen

**Comment by janiak-minova** [comment]
Wir wollen das soweit mergen, ganze Parts werden mit #1395 gelöst.
