### ISSUE TITLE
ParameterStrings: Zeit, Datum

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.rcp#1373]
Soweit ich @janiak-minova verstnden habe, wird bei der Kommunikation zwischen WFC/CAS Felder mit Zeitinformationen von der lokalen Zeitzone des WFC-Anwenders in die Zeitzone UTC umgewandelt, sobald diese zum CAS transferiert werden.

Bei `ParameterString` (http://nexus.minova.com:8000/Module/de.minova.doc/parameterstrings.html) kann ich das Verhalten teilweise nachvollziehen:
* '14.02.2023 07:23' in der lokalen Zeitzone CET wird zu '14.02.2023 06:23 UTC' (-1h)
* '31.08.2022' in der lokalen Zeitzone CEST wird zu '31.08.2022 00:00 UTC' (-2h) ist auch "ok"
* '10:46' in der lokalen Zeitzone CEST od. CET wird *nicht* zu '8:46 UTC' od. '9:46 UTC' konvertiert. 

Wenn ich Mitarbeiter A in der Zeitzone CEST und Mitarbeiter B in der Zeitzone GMT sitzen habe, wären meine Fragen hierzu:
- Wenn Mitarbeiter A '10:46' einträgt, welche Uhrzeit sieht Mitarbeiter B?
- Im ParameterString wird scheinbar der Datentyp `java.util.Date` für DateTime korrekt verwendet. Allerdings für Date und Time scheint er mißbraucht zu werden. Sollte nicht eher der Datentyp `String` verwendet werden? 

![Bildschirmfoto 2022-08-31 um 13 47 23](https://user-images.githubusercontent.com/95353437/187671823-1e2a302c-8b08-4dca-afd9-6acc32eba7e4.png)

**Comment by janiak-minova** [comment]
An das CAS werden alle Felder, die mit Zeit zu tun haben, als Instant geschickt, es wird Zeitzone UTC angenommen.

Nur bei Datum- UND Zeitfeldern wird die Zeitzone beachtet. An den Server werden sie im UTC-Format geschickt, von der Anwendung werden die Instants in der Zeitzone angezeigt.

Datumsfelder werden mit Uhrzeit 00:00 gespeichert, eine Umwandlung in eine Zeitzone findet NICHT statt.

Uhrzeitfelder werden mit Datum 01.01.1900 gespeichert, eine Umwandlung in eine Zeitzone findet NICHT statt.
