### ISSUE TITLE
Eingabe von "." (Grouping Seperator) in Zahlenfeldern

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1374]
<img width="126" alt="Bildschirmfoto 2022-08-31 um 14 48 13" src="https://user-images.githubusercontent.com/77741125/187681896-a137e3d3-05b8-4e93-bb48-74cad59af720.png">

Erwartung: Nach Eingabe von `.` springt der Cursor hinter den Punkt.

Aktuell: Cursor bleibt an gleicher Stelle stehen.

Frage: Was soll passieren, wenn der Cursor nicht direkt vor einem `.` steht?

**Comment by Bauer-David** [comment]
https://github.com/minova-afis/aero.minova.rcp/wiki/Felder-(inkl.-Datums--&-Zeitfelder) hier wird im Bereich Zahlenformatierung das richtige Verhalten beschrieben. Da wird auch explizit gesagt, dass Gruppierungstrennzeichen ignoriert werden
