### ISSUE TITLE
doppelte Spalte in Table?

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1387]
wieso wird denn hier ein Column-Name zweimal verwendet? Vielleicht wird irgendwann Table mal so verfeinert, dass mehrfache Verwendung des gleichen Namens abgewiesen wird. Die aktuelle Impl erlaubt mehrfache Verwendung, es kann aber nur auf die erste Spalte mit dem gesuchten Namen zugegriffen werden.

https://github.com/minova-afis/aero.minova.rcp/blob/5a89a369581128daddf1ff6214c83f235a587965/bundles/aero.minova.rcp.dataservice/src/aero/minova/rcp/dataservice/internal/DataService.java#L972

**Comment by janiak-minova** [comment]
In diesem Fall zeigt der Name der Spalte an, was für einen Datentyp die Zeile an der Stelle enthält (und wie damit umgegangen werden soll). 

Siehe  NotificationAndErrorAddon#formatMessage()
https://github.com/minova-afis/aero.minova.rcp/blob/master/bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/addons/NotificationAndErrorAddon.java#L109

Auf den Inhalt der Zeile kann zugegriffen werden, indem die Values der Zeile iteriert werden.
