### ISSUE TITLE
Nummernfelder werden nicht korrekt auf `null` gesetzt, wenn sie den Fokus haben

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1406]
Ausgangslage: Neuer Eintrag, Dirty-Flag nicht aktiv
<img width="588" alt="Bildschirmfoto 2022-12-22 um 10 22 54" src="https://user-images.githubusercontent.com/77741125/209101752-038b0b1c-2497-47ff-a2e6-aa07755921f0.png">

Wert in Double-Feld eintragen, Dirty-Flag aktiv:
<img width="584" alt="Bildschirmfoto 2022-12-22 um 10 23 45" src="https://user-images.githubusercontent.com/77741125/209101944-437192f4-ea7d-4865-aabe-301354cda812.png">

Nach Klick auf "Verwerfen" (Fokus im Double-Feld):
Erwartung: Double-Feld wird komplett geleert,  Dirty-Flag nicht aktiv
Ist-Zustand: Double-Feld wird auf `0,00` gesetzt, deswegen ist  Dirty-Flag aktiv
<img width="593" alt="Bildschirmfoto 2022-12-22 um 10 25 46" src="https://user-images.githubusercontent.com/77741125/209102394-84f22d80-886e-497f-9fce-bc18c1288cfe.png">

Ist der Fokus in einem andern Feld wird alles korrekt auf null gesetzt:
Vor "Verwerfen":
<img width="589" alt="Bildschirmfoto 2022-12-22 um 10 28 59" src="https://user-images.githubusercontent.com/77741125/209103079-23feb964-80ae-4144-8a39-88efe2e396ad.png">

Nach "Verwerfen":
<img width="589" alt="Bildschirmfoto 2022-12-22 um 10 27 49" src="https://user-images.githubusercontent.com/77741125/209102807-f6964120-f917-459b-8e3b-d8dddd187969.png">

Vielleicht wird das mit #1396 schon gelöst, sollte aber überprüft werden.

**Comment by Bauer-David** [comment]
wird durch #1396 gelöst
