### ISSUE TITLE
Enter öffnet die selektierte Sektion nicht

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#1414]
Beschreibung laut Doku: 
Anwendung: 12.7.3

(Zukünftig) Sections Öffnen und Schließen mit Enter (Dieses Element sollt dann auch Teil der TabListe sein) Der Benutzer soll in den Einstellungen einstellen können, ob er mittels Tab auf die Section selbst springen möchte oder nur auf die Felder in der Section.

https://github.com/minova-afis/aero.minova.rcp/issues/374

![Bildschirm­foto 2023-01-25 um 10 14 52](https://user-images.githubusercontent.com/20420898/214524243-5af6cde3-bd82-4981-822a-271ebd9524ae.png)

Das verhalten ist aktuell auf Windows und Mac gleich.

**Comment by Bauer-David** [comment]
Dieses Verhalten wurde am Anfang für den TraverseListener definiert. Da wir aber auf das Standardverhalten von Java umgestiegen sind, ist es nicht möglich auf die Sectionbars KEyBindings zu definieren. Daher ist die Implementierung des Öffnen mit Enter nicht möglich.

**Comment by Bauer-David** [comment]
Die Section können mit der Leertaste aus- und eingeklappt werden. Enter kann dafür nicht verwendet werden, da es für eine andere Funktion reserviert ist und daher der Listener nicht darauf reagiert.

**Comment by CE7** [comment]
Wurde in dem PullRequest von [KeyBinding - F3 Laden von Datensatz über MatchCode#1413](https://github.com/minova-afis/aero.minova.rcp/issues/1413) behandelt
