### ISSUE TITLE
Fehler bei Sonderzeichen in Lookups

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1430]
Gibt man in Lookups ein Sonderzeichen (z.B. `()*+`) ein, so erscheint ein Fehler.

![219383899-b1208431-2e37-46fd-8c34-e9297cf3fa6e](https://user-images.githubusercontent.com/77741125/219682319-e6fcaa47-4624-41cb-9747-fcbf0a17da64.png)

**Comment by wis36** [comment]
Eigentlich sind nicht alle Zeichen (#1431 ) und nicht "Sonderzeichen" an sich problematisch, sondern nur die Zeichen, die als RegEx interpretiert werden, also `()*+` und vermutlich auch `.-[]\`
