### ISSUE TITLE
Boolean-Felder über Tastatur bedienen

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.rcp#1435]
Scheinbar gab es in der alten Anwendung auch ein Verhalten für Boolean-Felder:

- [x] Mit Tab anwählen
- [x] Mit '+' das Feld auf true setzten
- [x] Mit '-' das Feld auf false setzen

**Comment by janiak-minova** [comment]
Mit Tab anwählen:

https://github.com/minova-afis/aero.minova.rcp/blob/master/bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/TabUtil.java#L47

In dieser Zeile fehlt der Check auf `Button`.

**Comment by wis36** [comment]
> Scheinbar gab es in der alten Anwendung auch ein Verhalten für Boolean-Felder:
> 
>     * [ ]  Mit Tab anwählen
> 
>     * [ ]  Mit '+' das Feld auf true setzten
> 
>     * [ ]  Mit '-' das Feld auf false setzen

in welcher alten Anwendung? ich kenne das nicht

**Comment by weber-minova** [comment]
> > Scheinbar gab es in der alten Anwendung auch ein Verhalten für Boolean-Felder:
> > ```
> > * [ ]  Mit Tab anwählen
> > 
> > * [ ]  Mit '+' das Feld auf true setzten
> > 
> > * [ ]  Mit '-' das Feld auf false setzen
> > ```
> 
> in welcher alten Anwendung? ich kenne das nicht

Alte Anwendung == Version 10&11

**Comment by wis36** [comment]
Tatsächlich, im Detailbereich funktioniert das. Again what learned 😎

**Comment by janiak-minova** [comment]
Unter Mac lassen sich leider die Buttons allgemein nicht mit Tab wählen.

Das Verhalten mit + und - zum Aus-/Entwählen der Checkbox funktioniert unter Windows automatisch.
