### ISSUE TITLE
Selektionskriterien speichern: Reihenfolge der Spalten bleibt gleich

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#1439]
Ich weiß nicht, ob die Spaltenreihenfolge nicht gespeichert wird oder ob es beim Laden ein Problem gibt, jedenfalls bleibt die Spaltenreihenfolge unverändert, wenn ich ein anderes Kriterium lade.

**Comment by janiak-minova** [comment]
Ich kann das nicht Nachstellen.

Ausgangslage, klicken auf "Speichern":
<img width="1417" alt="Bildschirmfoto 2023-02-28 um 16 43 47" src="https://user-images.githubusercontent.com/77741125/221903928-4b5ab3af-44f4-449a-8ee9-b1744941a57c.png">

Spaltenreihenfolge und -breite ändern:
<img width="1350" alt="Bildschirmfoto 2023-02-28 um 16 44 24" src="https://user-images.githubusercontent.com/77741125/221904167-4fb3f75c-374a-4ac6-a266-ddc583f9e420.png">

Nach Klick auf "Laden" ist die Ausgangslage wiederhergestellt. Das Gleiche im Index, inkl. Gruppierung und Sortierung.
<img width="1439" alt="Bildschirmfoto 2023-02-28 um 16 44 35" src="https://user-images.githubusercontent.com/77741125/221904247-6b6554ee-940f-4ba4-8fca-2357dda74b58.png">

**Comment by wis36** [comment]
Ich starte es direkt aus eclipse. Jetzt auch mit dem Stand vom Tag 12.7.4.

Nächste Woche würde ich es mal aus der exe starten und noch mal testen.

**Comment by janiak-minova** [comment]
Tatsächlich, lag wahrscheinlich an #1421, in dem der Nattable-Version auf 2.0.5 aktualisiert wurde.

**Comment by wis36** [comment]
So wie du es oben machst, klappt es bei mir jetzt wieder.

Mein konkreter Fall ist:
* Spalte Datum ganz nach vorn ziehen (Index)
* nach Datum wird auch gruppiert
* Speichern als DEFAULT
* noch irgendwas verändern (von&bis vertauschen)
* Laden von DEFAULT - die Vertauschung wird rückgängig gemacht, aber das Datum wandert auch zurück

**Comment by wis36** [comment]
Bei mir funktioniert es auch wieder, danke.
