### ISSUE TITLE
Klasse StaticXBSValueUtil um QuantityValue ergänzen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1462]
In der Klasse [StaticXBSValueUtil](https://github.com/minova-afis/aero.minova.rcp/blob/main/bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/StaticXBSValueUtil.java) muss noch ein case für QuantityValues ergänzt werden.

Die Klasse wandelt Strings aus der .xbs in die entsprechenden Values um. Siehe auch #1357.

Die [Doku](https://github.com/minova-afis/aero.minova.rcp/wiki/application.xbs#statische-werte) muss entsprechend ergänzt werden.

**Comment by CE7** [comment]
Das Problem ist, dass die Tests auf dem GitHub nicht durchlaufen. Das muss @janiak-minova  bitte nochmal prüfen.

**Comment by CE7** [comment]
Hier warten wir auf Lea.
