### ISSUE TITLE
Probleme bei der Stundenerfassung

### ISSUE THREAD

**Issue by weber-r** [minova-afis/aero.minova.rcp#1470]
![grafik](https://user-images.githubusercontent.com/112612556/232452714-b1a2dbdf-4515-45c7-979c-e35c7bf95530.png)
Tabellen lassen sich nicht ausklappen
Neustart von WFC und PC wurden bereits versucht

**Comment by janiak-minova** [comment]
Wir haben zusammen den Workspace per Hand gelöscht (also die Anwendung erst geschlossen, und die Dateien dann über den Explorer gelöscht).

Jetzt werden die Tabellen wieder angezeigt.
