### ISSUE TITLE
Wann soll 'FilterLastAction' bei Lookup-Resolve-Prozeduren (und Anfragen an Tabellen) gesetzt werde?

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1482]
Bei Resolve-Prozeduren von Lookups gibt es allgemein den Input `@FilterLastAction bit`.
Ähnlich kann man bei View/Tabellen-Anfragen auch nach LastAction filtern.

Aktuell wird in WFC beim Resolve immer nach LastAction > 0 gefiltert -> In Lookups können gelöschte Werte nicht aufgelöst werden.

Frage: 
Gibt es eine Regel, wann bei Resolve nach LastAction gefiltert werden soll und wann nicht (z.B. extra Variable in der Maske)? Spricht etwas dagegen, bei Resolve allgemein nie nach LastAction zu filtern?

**Comment by janiak-minova** [comment]
Verwandtes Problem: https://github.com/minova-afis/com.minova.oiltanking.twb/issues/1102 Journale und Journalvorlagen können nicht mehr gelöscht werden, wenn der Kontrakt gelöscht wurde, weil das Kontrakt-Lookup nicht mehr aufgelöst werden kann
-> Im WFC wird der Datensatz als "dirty" angezeigt
-> "dirty" Datensätze können nicht gelöscht werden.

**Comment by wis36** [comment]
Es gibt folgende Regel:
* in der List-Prozedur wird `FilterLastAction` so übergeben, wie es im Lookup-Feld definiert ist
  * z. B. `<lookup filter-last-action="true" procedure-prefix="spShippingOrderItem">`
  * Standard: `true`
* in der Resolve-Prozedur wird immer `FilterLastAction = 0` übergeben
