### ISSUE TITLE
Adressen im Default-Druck an Kunden anpassen

### ISSUE THREAD

**Issue by martins-1992** [minova-afis/aero.minova.rcp#1547]
Wir müssten mal die Adressdaten für die PDF-Generierung von Reports und co. mal einheitlich gestalten.
* [x] Im Index-Druck steht, glaube ich, immer die Minova-Adresse.
* [x] Im Detail-Druck kommt es von der generierten XML. Hier bräuchten wir aber eine Konvention, damit bspw. der SQL-Code für die XML-Generierung immer aus demselben Ort sich die Adressdaten holt.
* [x] Wie wird es für bspw. Rechnungen gemacht?

**Comment by theuerer** [comment]
Bei den Rechnungen werden die Layouts kundenspezifisch programmiert. Bei der Skytanking haben wir aktuell die Adresse pro Standort hardcodiert im Rechnungsformular.

Bei Rechungs-Detaildruck ermitteln wir aktuell in der SQl-Prozedur die Adresse  aus dem CompanyKey der tSite.

Die Ermittlung der Adresse erfolgte im 11-er aus der License.xbs. So wurde verhindert, dass jemand das System nutzt der der keine License.xbs hat.

**Comment by janiak-minova** [comment]
> der Detail-Druck über SQL-Code geht

Sorry, ja, die "spannenden" Daten funktionieren über SQL, siehe z.B. für [Invoice](https://github.com/minova-afis/aero.minova.invoice/blob/main/src/main/app/sql/xpcorXMLInvoiceDetail.sql).
Soweit ich das sehe wird aber in dem SQL Code nicht die Site ausgelesen, ich rate mal, die wurde auch in 11 von der Anwendung generiert und an den Anfang der xml Datei gepackt.

**Comment by theuerer** [comment]
> > der Detail-Druck über SQL-Code geht
> 
> Sorry, ja, die "spannenden" Daten funktionieren über SQL, siehe z.B. für [Invoice](https://github.com/minova-afis/aero.minova.invoice/blob/main/src/main/app/sql/xpcorXMLInvoiceDetail.sql). Soweit ich das sehe wird aber in dem SQL Code nicht die Site ausgelesen, ich rate mal, die wurde auch in 11 von der Anwendung generiert und an den Anfang der xml Datei gepackt.

Ja, die 11 hat die Adressdaten und Tel/Fax aus der License.xbs gezogen.  Ich fände es auch gut, wenn wir diese Daten auch wieder durch die Anwendung ermitteln und zur XML hinzufügen. Woher die Daten kommen müsste noch definierert werden.

Die SQL-Prozedur habe ich jetzt als "hotfix" vor Ort angepasst bis wir hier eine Definitionmj haben.

**Comment by janiak-minova** [comment]
Ich habe das Thema wie folgt umgesetzt:

- In der XBS können die Kunden-Daten wie in der alten license.xbs angegeben werden
- Diese Daten werden beim Index-, Detail und Statistikdruck mit in die xml formatiert, aus der dann die PDF erstellt wird
- Sind in den xsl Dateien entsprechende Felder definiert werden diese Daten angezeigt
- Sind die Felder in der XBS nicht definiert wird weiterhin die MINOVA Adresse verwendet


``` xml
<preferences>
	<root>
		<map />
		<node name="Settings">
			<map>
				<entry key="CustomerID" value="..." />
				<entry key="ApplicationID" value="..." />

				<entry key="siteaddress1" value="Anschrift" />
				<entry key="siteaddress2" value="Straße 123" />
				<entry key="siteaddress3" value="98765 Stadt" />
				<entry key="sitephone" value="0156 124134" />
				<entry key="sitefax" value="914 6134" />
				<entry key="siteemail" value="mail@test.de" />
			</map>
		</node>
		...
	</root>
</preferences>
```

Wenn wir auf CAS-Seite irgendwann umsetzten, dass die application.xbs Daten aus der Datenbank kommen können diese Werte dann auch automatisch gesetzt werden.

<img width="970" alt="Bildschirmfoto 2024-12-06 um 13 52 13" src="https://github.com/user-attachments/assets/440857db-ff72-47ac-b4dd-eb23972d4a86">

<img width="979" alt="image" src="https://github.com/user-attachments/assets/56d07cb0-1a54-47a3-b8bc-2bb77420af1a">

<img width="975" alt="image" src="https://github.com/user-attachments/assets/593a9f87-4fe9-4943-9a9b-798061b8b1c7">
