### ISSUE TITLE
Fehlermeldung für Fehler aus Helfer anzeigen

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#1559]
Wenn ein Fehler im Helfer auftritt, ist das nur über das WFC log ersichtlich z.B. über das Starten in Eclipse. Diese Fehlermeldung sollte auch im WFC Client angezeigt werden.

**Comment by janiak-minova** [comment]
Gerade wenn der Fehler in der setControls() Methode geschieht muss darauf geachtet werden, weil dann auch das weitere Initialisieren der Maske nicht funktioniert und ggf. die Knöpfe nicht korrekt angezeigt werden.
