### ISSUE TITLE
Excel Export als .xlsx statt .xls

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1590]
Der Excel Export des Index erstellt aktuell .xls Dateien.

"Neue" Excel Versionen beschweren sich beim Öffnen dieser Dateien, wir wollen stattdessen eine .xlsx Datei erstellen.

Siehe auch https://github.com/minova-afis/com.minova.oiltanking.twb/issues/1762.

**Comment by wis36** [comment]
Unterstützt das eine neuere NatTable-Version? Ansonsten müssten wir es ja selbst implementieren.
