### ISSUE TITLE
Ignorieren von Sections beim verwenden von TAB in der Detailansicht

### ISSUE THREAD

**Issue by KuemmertMinova** [minova-afis/aero.minova.rcp#189]
Derzeit wird beim verwenden von TAB auch der "Verwaltung Stundenerfassung" Reiter angepeilt. Dies soll nicht der Fall sein.

**Comment by BADMinova** [comment]
Die Fehler im Tab-Verhalten werden im Issue #374 gelöst. Für die Controls gibt es die Preference SelectAllControls, die das Selektieren erlaubt oder verbietet.
