### ISSUE TITLE
Abspeichern und Aktualisieren der Lookup-Optionen

### ISSUE THREAD

**Issue by KuemmertMinova** [minova-afis/aero.minova.rcp#203]
Bei den Lookup-Optionen müssen die Folgenden Punkte beachtet werden:

- Es werden nur dann Optionen vom CAS angefragt, wenn das Feld im Fokus ist
- Bei geänderten Parametern muss eine neue CAS Anfrage versendet werden
- Abspeichern der Optionen in der Lokalen Datenbank

**Comment by CE7** [comment]
Hier sollten wir einen weiteren Parameter in der XML-Maske einführen, der das Caching auch deaktivieren kann. Dann wird bei jeder Anfrage neugeladen! Dieser Parameter ist nur für Lookup Felder gültig.

Ansonsten ist das Caching bereits implementiert. (Lokal) 
Das bedeutet, dass die Anwendung so lange sie geöffnet ist, einen Cache füllt. (Hashmap Objekt). 
Soweit ich weiß ist es eigentlich aktiv. 

Andernfalls müsste man die Preferences erweitern und dort das interne Caching aktivierbar/deaktivierbar machen.

**Comment by janiak-minova** [comment]
Die offenen Punkte werden mit Issue #707 behandelt.
