### ISSUE TITLE
TraversListener, Verhalten mit Tab + Enter

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#214]
Benötigt #310 

**folgendes Verhalten wollen wir implementieren:** 

1. In das nächste Feld springen mit Hilfe von Tab
2. In das nächste Pflichtfeld (required=true) springen mit Enter
3. Ein Element aus der Vorschlagsliste (LookUP) übernehmen mit Enter
4. Ein Element aus der Vorschlagsliste (LookUP) übernehmen und in das nächste Feld springen mit Tab
5. (Zukünftig) Nach der Eingabe eines Feldes den ursprünglichen Wert eintragen mit ESC
6. (Zukünftig) Sections Öffnen und Schließen mit Enter (Dieses Element sollt dann auch Teil der TabListe sein) Der Benutzer soll in den Einstellungen einstellen können, ob er mittels Tab auf die Section selbst springen möchte oder nur auf die Felder in der Section.
7. (Zukünftig) Reihenfolge der Sektions individuell ändern: Ausnahme: Head, er steht immer ganz oben!

Für diese Umsetzung haben wir zusammen folgendes überlegt (ERC, SAW): 

- Verwendung des TraversListener. Dieser wird für die entsprechende UI Elemente registriert. 
- dynamisches auslesen der TabList: Wenn man mittels Tab in das nächste Feld springt oder (zukünftig) mittels Enter in das nächste Pflichtfeld, sollte die Liste der Sections immer frisch ausgelesen werden. 
- Pflichtfelder haben immer die Eigenschaft required=true (XML) 
- TabIndex soll nur innerhlab der Section eindeutig sein. Er beginnt immer bei 0. (gilt auf für sections) tab-index = 0(XML)
- Berücksichtigung der Felder mit der Eigenschaft read-only=true. Ggf. könnten diese Felder durch ein Event wieder auf false gesetzt werden, und wären dann auswählbar

**Verhalten (Tab)**
Mit Tab wird immer in das nächste Feld der Tab-Liste gesprungen. Ist dasletzte Feld aus der Tab-Liste bereits erreicht, so wird der Prozess auf der nächsten Section fortgesetzt. Wurde das Ende der letzten Section erreicht, springt man mit Tab in das erste zu selektierende Element in dem Detail (Button oder Feld)
Wenn eine _Section geschlossen_ wurden,  sollte der das Springen mit Tab diese Section überspringen.
Shift + Tab springt in das vorherige Feld.

**Verhalten (Enter) Pflichtfeld**
Sobald ein Pflichtfeld den Focus bekommt, sollte ein Wert eingetragen werden. Ist dies nicht der Fall, und man versucht in das nächste Pflichtfeld zu Springen mittels Enter sollte dies verhindert werden. Das Feld wird nur mit Tab verlassen, oder mit Enter, wenn ein gültiger Wert eingetragen wurde.
Wenn eine _Section geschlossen_ wurden,  sollte der das Springen mit Enter diese Section öffnen, wenn es in der Section ein leeres Pflichtfeld gibt.

**Suche nach dem nächsten Pflichtfeld**
Das nächste Pflichtfeld wird wie folgt gesucht: 
1. Gibt es in der Section noch Pflichtfelder unterhalb des aktuellen Feldes (Tabreihenfolge der Section beachten), welches nicht gefüllt ist
 1a.:Ja, dieses Auswählen 
 1b.: Nein, fortfahren mit nächster Section (Reihenfolge in control.parent().parent() beachten!--> weiter mit 2.
2. Leeres Pflichtfeld in der nächsten Section suchen (Reihenfolge = TabList aus aktueller Section)
 2a.: gefunden, dieses Auswählen
 2b.: nicht gefunden, wiederhole Schritt 1b.!

**Comment by janiak-minova** [comment]
Wird mit #310, #373 und #374 gelöst.
