### ISSUE TITLE
Ergebnisliste bei Dropdown markiert mehrere Einträge

### ISSUE THREAD

**Issue by ulf65** [minova-afis/aero.minova.rcp#234]
Wenn man eine Ergebnisliste eines Dropdowns mit den Cursortasten nach unten durchgeht, wird ab einem bestimmten Eintrag mehrere Einträge markiert.

![Stundenerfassung1](https://user-images.githubusercontent.com/60663214/107353041-de470100-6acc-11eb-8d7e-91011f680ce4.png)

Wenn man bei dem Eintrag bei dem man steht Enter drückt, wird dieser auch ausgewählt. Die Markierung wird auch nicht zurückgenommen, wenn man mit den Cursortasten nach oben geht.

**Comment by CE7** [comment]
Klasse: Lookup.java: Zeile 112
table = new Table(popup, SWT.SINGLE | SWT.H_SCROLL );

**Comment by janiak-minova** [comment]
Mit der Anpassung der Lookups, nur 15 Einträge zu zeigen (#425), scheint das Problem nicht mehr aufzutreten.
