### ISSUE TITLE
Nachladen von Applicationsdaten

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#236]
Um die Anwendung beim Client auf aktuell zu halten ist es nötig, dass die PlugIns und deren Stand überprüft werden können. 
Dafür ist ein HashCode vorgesehen. Ist der HashCode nicht identisch mit dem der Datei auf dem Server, muss die Datei ausgetauscht werden.

Für den Austausch vorgesehen sind folgende Dateien: 
* PlugIns
* XML Dateien
* XBS Dateien
* andere Jar Files
* properties Dateien

**Das Starten der Anwendung führt folgendes aus**

HashCodes sollen überprüft werden. 

1. Wenn der HashCode passt, bleibt die Datei auf dem Client-System. 
2. Passt er nicht, wird er vom Client-System entfernt.

Auf dem Server befindet sich ein Ordner / Ort mit aktuellen PlugIns der Client Anwendung. Beim Starten des Programms erfolgt die Überprüfung der HashCodes. Entspricht der HashCode einer Datei nicht dem HashCode von der Datei auf dem Server, sollte diese Datei auf den Client übertragen werden. 
Dieser Prozess wiederholt sich für alle PlugIns &  XBS-Dateien.
Zusätzlich werden alle "neuen" PlugIns und XBS-Dateien vom Server auf den Client übertragen.

Nachdem ein Update bereit gestellt wurde, muss der Anwender immer die Anwendung neustarten.

**Comment by janiak-minova** [comment]
Wird mit #680 behandelt.
