### ISSUE TITLE
Images in PlugIn

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#237]
Für das Anzeigen von Images in der Anwendung, in den Masken und OptionPages haben wir definiert, dass wir diese in einem Images-PlugIn eintragen. Dort befinden sich Ordner pro Icon, mit verschiedenen Dateigrößen (16x16,24x24,32x32,64x64,...) 

Es kann auch mehere Icon-PlugIns geben, diese stellen dann je nach Anwendung die entpsrechenden Icons bereit. 
Da es sich um ein PlugIn handelt werden diese Dateien wie in #236 beschrieben beim Starten der Anwendung aktualisiert. 

Aus der Datei sollen die Bilder der Masken, OptionPages und auch der Anwendung entnommen werden. 

Umsetzung:
- [ ] Pfade der Bilder so eintragen, dass Sie aus dem Images PlugIn geladen werden können
- [ ] Default-Pfad aus der application.xbs entnehmen
- [ ] Kann das Icon nicht gefunden werden, wird ein Default Bild eingefügt.
- [ ] Standard Icons werden innerhalb der RCP Anwendung verwaltet. Alle Icons die durch OPs oder Masken geladen werden müssen aus dem Image-PlugIn entnommen werden

**Comment by CE7** [comment]
Grundsätzlich ist es besser, dass wir die Bilder direkt in dem Modul der Maske ablegen, in der es gebraucht wird. Folgende Vorteile haben sich daraus ergeben: 
* Es werden tatsächlich nur die Bilder ausgeliefert, die auch gebraucht werden
* gleicher Mechanismus wie bei den Übersetzungen
* keine Probleme beim Ausliefern der OpenSource-Variante
Umsetzung: 

Parallel zu den Ordnern: i18n,setup,sql,tables soll es dann einen Ordner images erstellen.
Siehe Bild: 

![Bildschirmfoto 2021-09-29 um 08 37 37](https://user-images.githubusercontent.com/20420898/135215861-db2f3bf4-2105-4403-9ff6-e56c7083b61a.png)

**Comment by CE7** [comment]
Wir brauchen nur noch 4 Varianten; 
@2x varianten sind dann doppelt so groß wie die normalen Icons

* s --> 16x16
* m --> 32x32
* l --> 48x48
* xl --> 64x64

In der Toolbar sollten die Icons immer eine Größenordnung größer sein. Das bedeutet Größe "M" zeigt in der Toolbar die Icons von "L"

Daraus resultieren dann nur noch 4 verschiedene Themes!

**Comment by wis36** [comment]
Und was ist mit Images, die in mehreren / vielen Modulen benötigt werden?

**Comment by CE7** [comment]
Die würden dann doppelt drin liegen, weil wir ja nicht wissen, ob der Kunde beides verwendet.

**Comment by ingraban** [comment]
> Die würden dann doppelt drin liegen, weil wir ja nicht wissen, ob der Kunde beides verwendet.

Das stimmt nicht unbedingt. Die Bilder liegen ja in einem Modul. Wenn ein zweites Modul das Image verwendet, könnte es ja auch abhängig vom 1. Modul sein. Dann benötigt es das Image nicht im eigenen Code. 
Zum Anderen würden doppelte Images mit gleichen Namen ja nur einmal im Ordner liegen, der beim Bauen der `APP` erstellt wird.
