### ISSUE TITLE
Tab in Multiline Textfeldern

### ISSUE THREAD

**Issue by kos366** [minova-afis/aero.minova.rcp#241]
Man kann ein MultilineTextfeld (z.B. Beschreibung in WorkingTime.xml) nicht mehr mit TAB verlassen. Stattdessen wird ein TAB im Textfeld erzeugt. Das ist so nicht gewünscht. TAB ist als Eingabe gar nicht möglich.

Für Enter gilt das selbe, allerdings sollte mit STRG+Enter ein Umbruch erzwungen werden können.

**Comment by BADMinova** [comment]
Das Tab Verhalten wird im Issue #374 gelöst.
