### ISSUE TITLE
Suche in Dropdown Kombo Box funktioniert noch nicht

### ISSUE THREAD

**Issue by ulf65** [minova-afis/aero.minova.rcp#265]
Wenn man in eine Kombo Box etwas einträgt sucht der Client nicht danach, erst wenn man den Pfeil nach unten eingibt, werden die möglichen Ergebnisse angzeigt.

**Comment by CE7** [comment]
> Es sollte ja mehrere Möglichkeiten geben:
> 
>     * Eingabe von Text 😢
> 
>     * Pfeiltaste nach unten 👍
> 
>     * Pfeil mit der Maus klicken 👍
> 
>     * Verlassen des Feldes mit TAB oder ENTER 😢
> 
>     * CTRL-Space 😢

geht nun alles, wenn man im Popup ist, und mit Tab oder Enter bestätigt springt der Cursor in das nächste Feld.
