### ISSUE TITLE
Enter in Eingabefeld Beschreibung bewirkt kein Speichern

### ISSUE THREAD

**Issue by ulf65** [minova-afis/aero.minova.rcp#301]
Wenn man in der Stundenerfassung in der Beschreibung Enter drückt, geht der Cursor in die nächste Zeile. In der alten Stundenerfassung wurde das Speichern des Datensatzes ausgelöst.
Frage ist, will man das Verhalten so und falls ja braucht man meiner Meinung nach eine Tastenkombination die das Speichern auslöst.

**Comment by CE7** [comment]
Es soll genau so funktionieren wie in der Stundenerfassung

**Comment by CE7** [comment]
- [ ] Unter Windows sollte man mit ctrl + Enter eine neue Zeile editieren können. 

- [ ] Unter macOS sollte man mit command + Enter eine neue Zeile editieren können.

**Comment by Bauer-David** [comment]
Folgendes Verhalten wird bei den einzelnen Eingaben von Tab und Enter mit Modifier standardmäßig ausgeführt:


**Mac Tab:**
Ctrl + Tab = Benutzer bleibt im Feld und es wird keine Tab erstellt
Alt + Tab  = Benutzer bleibt im Feld und es wird eine Tab erstellt
Cmd + Tab = Unter den geöffneten Apps zur zuletzt verwendeten wechseln.

**Mac Enter:**
Ctrl + Enter = Benutzer bleibt im Feld und es wird ein Zeilenumbruch erstellt
Alt + Enter = Benutzer bleibt im Feld und es wird ein Zeilenumbruch erstellt
Cmd + Enter = Benutzer bleibt im Feld es wird kein Zeilenumbruch erstellt, es kommt ein Fehlersound

**Windows Tab**
Ctrl + Tab = Benutzer bleibt im Feld und es wird keine Tab erstellt
Strg + Tab/ Fn + Ctrl + Tab =  Benutzer bleibt im Feld und es wird eine Tab erstellt
Alt + Tab = Windows spezifisches Verhalten wechseln zur letzten Anwendung
Win + Tab/ Fn + Cmd + Tab = Windows spezifisches Verhalten Übersicht aller offenen Fenster

**Windows Enter**
Ctrl + Enter = Benutzer bleibt im Feld und es wird ein Zeilenumbruch erstellt
Strg + Enter/ Fn + Ctrl + Enter =  Benutzer bleibt im Feld und es wird kein Zeilenumbruch erstellt
Alt + Enter = Benutzer bleibt im Feld und es wird kein Zeilenumbruch erstellt
Win + Enter/ Fn + Cmd + Enter = Benutzer bleibt im Feld und es wird kein Zeilenumbruch erstellt

**Comment by Bauer-David** [comment]
Die beiden Probleme bzw. gewünschten Ergänzungen werden in anderen Tickets einzeln behandelt:

Speichern mit Enter => #562 
Leerzeile und Tab im Beschreibungsfeld => #563
