### ISSUE TITLE
Beschreibungsfeld wird nicht auf Länge geprüft

### ISSUE THREAD

**Issue by ulf65** [minova-afis/aero.minova.rcp#302]
Wenn man in der Stundenerfassung etwas in die Beschreibung einträgt wird nicht auf die maximale Länge des Datenbankfelds geprüft und der Benutzer darauf hingewiesen. Außerdem bricht der Text am Ende des sichtbaren Bereichs nicht um.

In der alten Anwendung wurde das Feld rot, sobald man aus der Beschreibung mit Tab rausgesprungen ist. Außerdem ist der Text automatisch umgebrochen worden.

Umsetzung: 
Es gibt einen Parameter in der XML-Maske, der die Länge des Textes definiert. 
Dieser muss abgefragt und mit der User-Eingabe verglichen werden. Ist die Usereingabe länger als die definierte Textlänge, könnten wir dem User dies visuell anzeigen

<img width="594" alt="Bildschirmfoto 2021-04-16 um 10 23 21" src="https://user-images.githubusercontent.com/20420898/114995173-d5442880-9e9d-11eb-8550-f3d941c44ef4.png">

**Comment by CE7** [comment]
"Außerdem ist mir aufgefallen, dass wenn man einen überlangen Text bucht, bleibt der Text in der Beschreibung stehen."
Wurde korrigiert
