### ISSUE TITLE
Mehrfachsortierung im Index

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#320]
Aktuell ist keine Mehrfachsortierung möglich.

Für die NatTable in Stand 11 hatten wir das in trac#22441 gelöst, mit ALT+Klick, das ist sogar eine Standard-NatTable-Konfiguration. Leider funktioniert es unter Linux nicht, weil dort ALT+Klick bereits anderweitig vergeben ist.

**Comment by kos366** [comment]
Lustige Idee, unter Linux 'Shift-Click' zu verwenden. Wie in jedem Betriebssystem markiert 'Shift-Click' aber alles von der letzten Markierung bis zur angeklickten Stelle, ist also auch unbrauchbar. 'Shift-ALT-Click' funktioniert aber. 

Somit auch unter Linux gelöst.
