### ISSUE TITLE
Fehlermeldung beim Sortieren nach Uhrzeiten

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.rcp#339]
Wenn man im Index-Bereich die Columns nach 'Von' oder 'Bis' sortiert, tritt folgende Fehlermeldung auf:

<img width="720" alt="Bildschirmfoto 2021-03-19 um 10 49 33" src="https://user-images.githubusercontent.com/75690564/111762485-590bf480-88a1-11eb-8d29-47edbe634c8e.png">

Klickt man danach noch einmal auf 'Von' oder 'Bis' stürzt die Anwendung komplett ab.
Sowohl im momentanen Release als auch auf dem Master.

**Comment by janiak-minova** [comment]
Mit #430 tritt kein Fehler mehr auf, wenn nach 'Von' oder 'Bis' sortiert wird. Damit müssen die Daten auch nicht bereinigt werden.
