### ISSUE TITLE
Add Formatting rules zum Projects um einheitliches Formatieren zu gewährleisten

### ISSUE THREAD

**Issue by vogella** [minova-afis/aero.minova.rcp#362]
In einigen Commits sehe ich Formatierungsänderungen, das macht das manchmal schwer die eigentlich Änderung zu sehen, hier sollten wir die Formatierungsregeln auf Projektebene einstellen damit alle die gleichen Regeln nutzen.

cc @BADMinova @CE7

**Comment by janiak-minova** [comment]
Wir benutzen die Formatierung, wie sie [hier (Punkt 3.6)](http://nexus.minova.com:8000/Module/de.minova.doc/eclipse.html) beschrieben ist.
