### ISSUE TITLE
Stundenerfassung: Journalsatz kann ohne Mitarbeiter gespeichert werden

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#379]
Wahrscheinlich war tatsächlich kein Mitarbeiter eingetragen. Es gibt bestimmt schon einen Issue dass das nicht automatisch passiert?

Jedenfalls sollte ohne Mitarbeiter nicht gespeichert werden - es sollte in der Maske ein Pflichtfeld sein. Ich denke es wäre auch sinnvoll, das in der Prozedur abzufangen.

**Comment by janiak-minova** [comment]
Wird mit #426 gelöst.
