### ISSUE TITLE
Passwort wird nicht gespeichert

### ISSUE THREAD

**Issue by OlliDob** [minova-afis/aero.minova.rcp#388]
Beim Anlegen eines Profiles gebe ich mein Netzwerkapasswort ein und die Anwendung lässt sich öffnen und funktioniert ohne Probleme.

Wenn ich die Anwendung schließe und wieder öffne, kommt die Fehlermeldung "User oder Passwort nicht korrektnull"

![Bildschirmfoto 2021-04-01 um 10 05 04](https://user-images.githubusercontent.com/77635124/113263209-c6704a00-92d1-11eb-8418-149ccb7ecc95.png)

**Comment by CE7** [comment]
Wenn man wie folgt vorgeht vorgeht, kann man den Fehler reproduzieren: 
1. Profil ohne PW anlegen und verbinden
2. Nach Fehlermeldung PW eintragen und Verbinden
3. Wiederholt nach dem Neustart das Profil auswählen und verbinden

**Comment by janiak-minova** [comment]
Weiteres Problem:

1. Profil mit falschem Passwort anlegen und verbinden
2. Nach Fehlermeldung neustarten
3. Profil auswählen und verbinden
4. Bei neuen Anmeldeversuchen mit diesem Profil ist ein einloggen wegen falschem Passwort nicht möglich

**Comment by janiak-minova** [comment]
Außerdem funktioniert ein Profil nicht mehr, wenn sich das Passwort geändert hat.
