### ISSUE TITLE
Schrift-/Icon-/ect. Größen verstellen in den Preferences funktioniert noch nicht

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.rcp#399]
Die Schrift und Icons der Anwendung sind etwas klein und Manche haben dadurch Probleme bei der Bedienung.
Dabei ist aufgefallen, dass die Reiter (siehe Bild) nichts bewirken.
<img width="346" alt="Bildschirmfoto 2021-04-07 um 14 19 39" src="https://user-images.githubusercontent.com/75690564/113865643-9bdc3080-97ac-11eb-8a22-3a13c2f934bd.png">

**Comment by janiak-minova** [comment]
Wird mit #894 gelöst, Einstellungen für Schriftgröße und Icons wird zusammengenommen.
