### ISSUE TITLE
Felder von Datentyp DateTime werden nicht im Detail angezeigt

### ISSUE THREAD

**Issue by bambusbjorn** [minova-afis/aero.minova.rcp#400]
In der Maske CTSTestZeitraum gibt es zwei Felder vom Datentyp Datetime. 

Beim Starten der WFC Anwendung und öffnen der Maske wurden die Felder nicht angzeigt. 

Mit Martins uns Kerstin haben wir den Datentyp der Felder in der Maske auf dem Server in ShortDate geändert und nach einem Neustart wurden die Felder angezeigt. 

Ich musste erst beide Datentypen ändern, damit ich die Felder sehen konnte. Aber vielleicht lag das nur daran, dass die Felder in einer Zeile stehen

**Comment by janiak-minova** [comment]
Inzwischen können auch Felder mit Datentyp DateTime erstellt werden.
