### ISSUE TITLE
SearchPart zeigt falsche Daten an, wenn man die Spaltenbreiten optimiert und ein Feld noch fokusiert ist

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#408]
<img width="574" alt="Bildschirmfoto 2021-04-09 um 10 30 19" src="https://user-images.githubusercontent.com/20420898/114152421-969ef300-991e-11eb-9113-b07d50530f44.png">

**Comment by janiak-minova** [comment]
Wurde mit #412 gelöst.
