### ISSUE TITLE
Pflichtfelder implementieren

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#426]
Das Verhalten von Pflichtfeldern muss noch angepasst werden. Dazu gehört:

- [x] Speichern ist nur möglich, wenn alle Pflichtfelder ausgefüllt sind
- [x] Nicht ausgefüllte Pflichtfelder werden farblich hervorgehoben

**Comment by CE7** [comment]
<img width="596" alt="Bildschirmfoto 2021-04-16 um 10 55 22" src="https://user-images.githubusercontent.com/20420898/114999553-3ff76300-9ea2-11eb-8314-3d42f5df3c64.png">


Sobald ein Pflichtfeld keinen Wert mehr trägt wird es mit einem orangen Hintergrund angezeigt. Füllt man dieses Feld mit einem gültigen Wert, wird es nach dem Verlassen weiß.
Füllt man es mit einem ungültigen Wert wird es rot.

**Comment by CE7** [comment]
<img width="555" alt="Bildschirmfoto 2021-04-16 um 10 56 55" src="https://user-images.githubusercontent.com/20420898/114999790-77660f80-9ea2-11eb-970c-1295c682868d.png">
