### ISSUE TITLE
Editing support im NatTable einbauen

### ISSUE THREAD

**Issue by vogella** [minova-afis/aero.minova.rcp#43]
Primitive Lösung sollte sein:

natTable.addConfiguration(new AbstractRegistryConfiguration() {
	@Override
	public void configureRegistry(IConfigRegistry configRegistry) {
		configRegistry.registerConfigAttribute(EditConfigAttributes.CELL_EDITABLE_RULE,
				IEditableRule.ALWAYS_EDITABLE);
	}
});

Aber wahrscheinlich wollen wir spezifische Editoren für die Felder. Gibt es da Kundenspezifische Editoren in der alten Lösung? Oder werden nur Standardeditoren verwendet? Ich vermute die Editoren sind abhängig von den Datentypen in der Row.

**Comment by janiak-minova** [comment]
Funktioniert
