### ISSUE TITLE
Anwendung hängt, wenn Tickets nicht aufgelöst weden können

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#438]
Wenn beispielsweise die Verbindung zum Ticketserver / Cas nicht mehr zur Verfügung steht, hängt die Anwendung wenn man ein Ticket auflösen möchte: 

Gerade gab es eine Störung: 16:56Uhr 19.04.2021

Die Anwendung bleibt dann in diesem Zustand stehen!

<img width="495" alt="Bildschirmfoto 2021-04-19 um 13 59 04" src="https://user-images.githubusercontent.com/20420898/115232778-683bc780-a117-11eb-9295-3ffa7375d26c.png">

**Comment by janiak-minova** [comment]
Wird mit #440 behandelt.
