### ISSUE TITLE
Workspaces müssen manchmal neu angelegt werden

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#444]
Mit neuen Masken oder Versionen der Anwendung müssen manchmal neue Workspaces angelegt werden.

In der CTS-Anwendung trat etwa eine unerwartete Cast-Exception auf (siehe Anhang).
[ATT93277.log](https://github.com/minova-afis/aero.minova.rcp/files/6342490/ATT93277.log)

Außerdem werden neue Masken teilweise mit xml Fragmenten heruntergeladen, sodass diese gelöscht und neu geladen werden müssen.

**Comment by janiak-minova** [comment]
> Außerdem werden neue Masken teilweise mit xml Fragmenten heruntergeladen, sodass diese gelöscht und neu geladen werden müssen.

Dieses Problem wird mit #480 gelöst.

**Comment by vogella** [comment]
Duplicate von #480
