### ISSUE TITLE
Problem mit Lookup-Feldern unter Windows

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#448]
Unter Windows können die Lookup-Felder nicht korrekt bedient werden.

Es kann nur jeweils ein Zeichen eingetragen werden, dann wird der Fokus auf das Popup mit Vorschlägen gesetzt und das Zeichen aus dem Feld gelöscht.
Wenn der Fokus nicht gesetzt wird, kann die Scrollbar nicht über klicken und ziehen bedient werden.

**Comment by janiak-minova** [comment]
Wir glauben, dass das Popup zu früh auf unsichtbar gesetzt wird, wahrscheinlich in Zeile 121 oder 300 (Lookup.java).

**Comment by CE7** [comment]
Unter macOS werden die Lookups wie folgt dargestellt. 
* Suche eines Begriffes aus der Liste kann in der Textbos erfolgen. Der Text in dem Feld bleibt stehen und die Liste filtert nach dem gesuchten Text
![Bildschirmfoto 2021-04-22 um 08 38 26](https://user-images.githubusercontent.com/20420898/115667421-1cbb3080-a346-11eb-9f29-a19047747553.png)

Unter Windows ist das Verhalten leider falsch.
Hier wird der eingegebene Text nicht weiterhin angezeigt.
![Bildschirmfoto 2021-04-22 um 08 47 05](https://user-images.githubusercontent.com/20420898/115668367-52144e00-a347-11eb-957f-70a427ef0283.png)
Wenn ein Element in dem Popup ausgewählt wurde, kann man über die Eingabe der Tastertur auch filtern, leider sieht man dabei seine Eingabe nicht mehr.
