### ISSUE TITLE
Falsches Verhalten bei ENTER und Lookups 

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#455]
Ausgehend von folgenden Einstellungen: 

![Bildschirmfoto 2021-04-22 um 13 24 38](https://user-images.githubusercontent.com/20420898/115706620-25bff800-a36e-11eb-8b6e-8df9f0a885e8.png)

Folgendes Szenario führt zu einem Fehlverhalten:
Wählt man aus der Lookup "Projekt" einen Eintrag aus und bestätigt Ihn mit "Enter" landet man wieder in Kunde anstatt in dem nächsten Feld. 

![Bildschirmfoto 2021-04-22 um 13 22 58](https://user-images.githubusercontent.com/20420898/115706887-6881d000-a36e-11eb-9f72-94726631183c.png)
![Bildschirmfoto 2021-04-22 um 13 23 05](https://user-images.githubusercontent.com/20420898/115706892-6c155700-a36e-11eb-8e93-fa7e9ebd5a1e.png)

**Comment by Bauer-David** [comment]
Die Ermittlung des nächsten Pflichtfeldes wurde wie folgt angepasst:

In der Folgenden Beschreibung ist die Preference EnterSelectsFirstRequired nicht gesetzt oder das Popup des Lookups ist offen und die Preference LookupEnterSelectsNextRequired ist gesetzt.

Es wurde die Reihenfolge bestimmt in der die Felder geprüft werden, ob sie nicht ausgefüllte Pflichtfelder sind. Die Prüfung beginnt mit den Feldern , die sich in der selben Section befinden und nach dem ausgewählten Feld. Danach werden die Felder der nachfolgenden Section geprüft. Wenn mann bei der letzten Section angekommen ist, werden die Section vom Index 0 aus geprüft, bis man wieder bei der Section des ausgewählten Feldes angelangt ist. Dann werden die Felder in der Section des ausgewählten Fields geprüft die vor diesem stehen.

Falls bei einer der Prüfungen ein Feld gefunden wird, endet die Prüfung und das Feld wird selektiert.
