### ISSUE TITLE
"Enter" überspringt keine gefüllten Felder

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#456]
![Bildschirmfoto 2021-04-22 um 13 24 38](https://user-images.githubusercontent.com/20420898/115707322-ec3bbc80-a36e-11eb-8e51-218e9b5c73b1.png)

Wenn wir in dem Feld Kunde "Enter" betätigen sollte das letzte freie Feld aus dem Head angewählt werden!
![Bildschirmfoto 2021-04-22 um 13 30 54](https://user-images.githubusercontent.com/20420898/115707446-15f4e380-a36f-11eb-8c9e-4581308c10e4.png)
![Bildschirmfoto 2021-04-22 um 13 31 00](https://user-images.githubusercontent.com/20420898/115707455-18573d80-a36f-11eb-8d6e-c6ed616c6511.png)

**Comment by Bauer-David** [comment]
Die Ermittlung der Pflichtfelder wurde um die Prüfung des Values erweitert. Dies hat zu folge, dass nur Pflichtfelder dessen Value == null ist mit Enter ausgewählt werden können.
