### ISSUE TITLE
Popup bleibt offen, wenn Feld aus lookup mit Enter bestätigt wurde

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#457]
![Bildschirmfoto 2021-04-22 um 16 46 20](https://user-images.githubusercontent.com/20420898/115734895-57df5300-a38a-11eb-8f73-b4e3f45264f4.png)

Wenn die Einstellungen entsprechend gewählt wurden, sollte die Auswahl des Wertes auch das Popup schließen!

![Bildschirmfoto 2021-04-22 um 16 46 11](https://user-images.githubusercontent.com/20420898/115734904-59108000-a38a-11eb-857a-1a0737d1c210.png)

**Comment by Bauer-David** [comment]
Das Popup wird nun geschlossen, wenn der Benutzer im selben Feld landet, wenn er Enter drückt.
