### ISSUE TITLE
Löschen eines Zeitwertes führt zu falscher Cursor-Position

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#458]
Beim Versuch die bereits eingetragenen Bis oder Von-Zeiten zu entfernen, ist der Cursor auf der falschen Position und der Wert lässt sich nicht löschen.

![Bildschirmfoto 2021-04-22 um 16 50 46](https://user-images.githubusercontent.com/20420898/115735858-18fdcd00-a38b-11eb-95ae-bdfc71c2b846.png)
![Bildschirmfoto 2021-04-22 um 16 50 51](https://user-images.githubusercontent.com/20420898/115735871-1ac79080-a38b-11eb-8370-21bd2d9c1926.png)

**Comment by Bauer-David** [comment]
Dieses Verhalten wurde mit Wilfried besprochen und genau so auch dokumentiert in der README.adoc vom Modul rcp.rcp.

**Comment by CE7** [comment]
Wurde bereits gelöst mit Merge von Ticket #521
