### ISSUE TITLE
Anwendung hängt, neuladen nicht möglich

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#468]
Mir ist jetzt schon das 3. Mal passiert, dass die Annwendung nach dem Speichern und Neuladen hängt: 

![Bildschirmfoto 2021-04-27 um 14 24 25](https://user-images.githubusercontent.com/20420898/116240749-79628500-a764-11eb-8e99-0c603b8042e3.png)
Der Button um den Index zu laden bleibt "grau" und kann nicht mehr betätigt werden.

Aufgefallen ist mir das seit dieser Woche. Getestet mit Version 12.0.15

Könnte es auch ein Problem mit dem Server geben? (Stundenerfassung)

**Comment by janiak-minova** [comment]
Gehört wahrscheinlich zu #440, wenn der Server nicht antwortet

**Comment by wis36** [comment]
Ich hatte das auch vor 1-2 Wochen schon mal.

**Comment by janiak-minova** [comment]
Mit #479 wird der Laden Knopf wieder freigegeben, wenn keine Antwort vom Server kommt.

**Comment by janiak-minova** [comment]
Wird mit #440 behandelt
