### ISSUE TITLE
Umbaue des Tab Verhaltens

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#485]
Das Tab Verhalten wird nicht mehr durch den TraverseListener geregelt. Wir verwenden die Verhaltens Implementierung von Eclipse. Diese Entspricht dem Standard Verhalten des Systems. Für die Umsetzung müssen die untern Schritte abgeschlossen werden:

- [x] TabListen in den Sections bestimmen(composite.setTabList())
- [x] TabListe des DetailParts anpassen, um die Selektion der SectionsControls und der Toolbar zu ermöglichen (Preference SelectAllControls)
- [x] Verhalten im Beschreibungsfeld für Tab + Modifier ermöglichen

**Comment by janiak-minova** [comment]
Im Text der Preference.SelectAllControls sollte dabeistehen, dass das Verhalten von Tab beeinflusst wird.
