### ISSUE TITLE
Schließen der letzten Perspective über den Perspective Switcher (Toolbar am Boden) führt zur NPE

### ISSUE THREAD

**Issue by vogella** [minova-afis/aero.minova.rcp#502]
Wenn die letzte Perspective geschlossen wird, wird versucht eine andere zu aktivieren, was zu einer NPE führt.

**Comment by CE7** [comment]
Wenn die letzte Perspektive geschlossen wird, sollte wie auch beim 1. Starten der Anwendung ein leerer Bereich angezeigt werden.

**Comment by CE7** [comment]
Ich habe fertig!
