### ISSUE TITLE
Detail um Dirty-Flag erweitern

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#509]
Das Detail sollte um ein Dirty-Flag erweitert werden.

Damit is es möglich, die Nutzer darauf hinzuweisen, dass sich Einträge durch Nutzereingaben geändert haben, etwa bevor ein neuer Eintrag aus dem Index geladen wird.
Entsprechend soll sich ein Fenster öffnen, mit dem es möglich ist, die Änderungen zu speichern, zu verwerfen, oder den Prozess abzubrechen.

**Comment by CE7** [comment]
Umgesetzt wurde das folgende: 

- [ ] Dirtyflag pro Perspektive setzen
- [ ] Rückfrage beim Schließen der Anwendung ob nicht gespeicherte Perspektiven verworfen werden sollen
- [ ] Visuelle Anzeige in aktuellem Detail-Bereich, wenn Dirtyflag activ
- [ ] Dirtyflag automatisch zurücksetzen, wenn Ursprüngliche Daten wieder eingetragen wurden

offene Themen: 
- [ ] Dirtyflag auch an Toolbar-elemente hängen
- Rückfrage wenn DirtyFlag activ bei verschiedenen Scenarien: 
- [ ] Laden eines anderen Datensatzes aus dem Index
- [ ] Neuen Datensatz erstellen
