### ISSUE TITLE
Workspaces müssen neu angelegt werden

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#519]
Wenn die Application.e4xmi geändert wird oder neue Plug-Ins hinzugefügt werden, müssen die alten Workspaces gelöscht oder mit -clearPersistedState geöffnet werden. 

Dies sollte nicht nötig sein, oder es sollte eine Möglichkeit geben, den Workspace über die Anwendung selbst zu reparieren.

**Comment by vogella** [comment]
Für commands und handlers lösen wir das über ein Fragment und dem zusätzlichen Attribute "persistState=false" für diese Element.
