### ISSUE TITLE
Anwendungs-Icon in Fenster-Titelleist fehlt.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#522]
Ich nehme an, dass es MacOS auch betrifft.

![grafik](https://user-images.githubusercontent.com/7956931/117959276-23710e00-b31c-11eb-9a97-d9a4a8645767.png)

**Comment by vogella** [comment]
Beim Window wurde die Icon URI nicht gesetzt. Nach dem Setzen ist -clearPersistedState notwendig, um das korrekt zu übernehmen.

**Comment by vogella** [comment]
Gefixed, bitte under Windows überprüfen.
