### ISSUE TITLE
Alle Tests sollten JUnit5 nutzen

### ISSUE THREAD

**Issue by vogella** [minova-afis/aero.minova.rcp#535]
Aktuell sind die Tests eine Mischung von JUnit4 und JUnit5. Wir sollten alles auf JUnit5 migrieren.

**Comment by janiak-minova** [comment]
Mit [7ac3d57](https://github.com/minova-afis/aero.minova.rcp/commit/7ac3d578ed43e506145dcd7bfa6473da1744a752) wurden (hoffentlich) alle JUnit4 Tests auf JUnit5 migriert.

**Comment by janiak-minova** [comment]
[8dcca9d](https://github.com/minova-afis/aero.minova.rcp/commit/8dcca9daf750a50121d6c5c7335cb0d521bc4a5e) hatte noch welche verpasst.
