### ISSUE TITLE
Übersetzungen nicht alle einheitlich auf Deutsch

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#539]
Wann man einen Datensatz zu gleichen Zeit erfasst, kommt die Meldung, dass dieser Datensatz bereits eingetragen ist. Leider wird die Übersetzung nicht verwedent. Die Mledung kommt immer auf Englisch

**Comment by CE7** [comment]
Bitte schaut euch mal die Übersetzungen an und ergänzt die fehlenden Texte. Dann müssten wir die i18n nochmal auf dem Server austauschen für die Stundenerfassung

**Comment by janiak-minova** [comment]
Ich würde das gerne gleich ordentlich machen, und die Übersetzungen alle in die Projekte [aero.minova.app.i18n](https://github.com/minova-afis/aero.minova.app.i18n) (für allgemeine Übersetzungen) bzw. [aero.minova.workingtime](https://github.com/minova-afis/aero.minova.workingtime) (für Übersetzungen spezifisch zur Stundenerfassung) eintragen.

**Comment by weber-minova** [comment]
> Ich würde das gerne gleich ordentlich machen, und die Übersetzungen alle in die Projekte [aero.minova.app.i18n](https://github.com/minova-afis/aero.minova.app.i18n) (für allgemeine Übersetzungen) bzw. [aero.minova.workingtime](https://github.com/minova-afis/aero.minova.workingtime) (für Übersetzungen spezifisch zur Stundenerfassung) eintragen.

Übersetzungen aus den Projekt werden nun verwendet.
