### ISSUE TITLE
Arbeitszeit füllen fehlt

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#540]
In der alten Stundenerfassung konnte man über einen Button die Arbeitszeit füllen. 

![Bildschirmfoto 2021-05-19 um 13 23 07](https://user-images.githubusercontent.com/20420898/118804954-a27abf00-b8a5-11eb-9d30-4fb4ab4fa936.png)

Es wurden dann für alle Tage die im Von / Bis Bereich liegen eine Ticket erfasst. 
Das Ticket wird dem den Eigeschaften aus der Standard-Maske erstellt. 
![Bildschirmfoto 2021-05-19 um 13 23 26](https://user-images.githubusercontent.com/20420898/118804945-a0b0fb80-b8a5-11eb-9d72-38c4df0f90ef.png)

Es sollte in dem Helper eingetragen werden!

Button gehen noch gar nicht, dafür müssen wir uns noch ein Konzept überlegen.

**Comment by weber-minova** [comment]
duplikat #437
