### ISSUE TITLE
Falscher Wert wird für "Aufwand" erfasst

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#541]
Wenn man in der Stundenerfassung versucht das Ticket #51888 zu erfassen wird "ZWARTUNG" anstatt "Z-WARTUNG" für "Aufwand" erfasst.

**Comment by wis36** [comment]
Ist in der alten Stundenerfassung genauso. Das liegt daran, dass die Abrechnungsdaten im Ticket nicht korrekt hinterlegt sind.

PROJEKT ist nicht zulässig, mögliche Felder die ausgelesen werden:
(Kunde|Projekt|Kontrakt|Aufwand|Beschreibung)
