### ISSUE TITLE
Falsche Übersetzung für die Stundenerfassung

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#549]
In der Stundenerfassung wurden die Felder Von / Bis falsch übersetzt. 
![Bildschirmfoto 2021-05-25 um 13 16 48](https://user-images.githubusercontent.com/20420898/119489157-af8f2680-bd5b-11eb-882e-58a070033084.png)

Es sollte eigentlich: 
* Zeit = Von
* Von = Bis heißen

**Comment by CE7** [comment]
So sollte es aussehen: 

![Bildschirmfoto 2021-05-25 um 13 19 59](https://user-images.githubusercontent.com/20420898/119489375-ea915a00-bd5b-11eb-81be-be1ca4f6b63f.png)

**Comment by janiak-minova** [comment]
Ist aktualisiert.
