### ISSUE TITLE
Icons im Detail werden um 180° Grad gedreht wenn eine Datensatz nicht eingetragen werden konnte

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#557]
Sehr stranges Verhalten bei Fehlermeldungen vom CAS in der Stundenerfassung. 
Bei dem Versuch einen Datensatz zu speichern, bei dem der Servicekey falsch ist, wird eine Fehlermeldung geworfen. Während diese Meldung sichtbar ist, sind die Icons im Detailbereich gedreht. 

![Bildschirmfoto 2021-05-28 um 09 11 54](https://user-images.githubusercontent.com/20420898/119944843-0fbcdd00-bf95-11eb-8861-53c8d0785612.png)

**Comment by janiak-minova** [comment]
Fehlermeldung erscheint beim Erfassen von Ticket #27591.

**Comment by CE7** [comment]
Ich habe bemekt, dass es auch in der Dispo App vorkommt. Es liegt eher am Eclipse als an der Anwendung. Oder an meinem PC
