### ISSUE TITLE
Nachladen von geschlossenen Perspektiven funktioniert nicht

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#577]
Wenn man eine Perspektive mit "keepIt" an die Buttombar anheftet, wird nach dem Schließen dieser Perspektive nichts angezeigt. Wenn man die gleiche Maske über das Menu wieder öffnet ist sie kaputt!

Nach dem wiederholten Laden liegt eine Datei in der WorkSpaceLocation, die den gleichen Namen trägt wie die ID aus der application.mdi Datei. Dieses Problem muss gelöst werden!

**Comment by janiak-minova** [comment]
<img width="1447" alt="Bildschirmfoto 2021-05-31 um 16 32 48" src="https://user-images.githubusercontent.com/77741125/120208599-f2ef0680-c22d-11eb-8a10-6bab7bc3ed0c.png">
