### ISSUE TITLE
Mehrere Zeilen im Index selektieren deaktivieren

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#617]
Aktuell kann man im Index mehrere Zeilen auswählen. Da dies für keine Funktionalität benötigt wird, soll jeweils nur eine Zeile gewählt werden können.

**Comment by CE7** [comment]
In der alten Anwendung ist folgendes Verhalten zu erkennen: 
* Selektion mittels "Shift" + MouseDown lädt lediglich den ersten markierten Eintrag im Index
* Selektion mittels "Shift" + ArrowDown lädt lediglich den ersten markierten Eintrag im Index
* Selektion mittels "Shift" + ArrowUp lädt jeweils den obersten Eintrag
* Multiselekt soll grundsätzlich möglich sein.

**Comment by CE7** [comment]
> In der alten Anwendung ist folgendes Verhalten zu erkennen:
> 
>     * Selektion mittels "Shift" + MouseDown lädt lediglich den ersten markierten Eintrag im Index
> 
>     * Selektion mittels "Shift" + ArrowDown lädt lediglich den ersten markierten Eintrag im Index
> 
>     * Selektion mittels "Shift" + ArrowUp lädt jeweils den obersten Eintrag
> 
>     * Multiselekt soll grundsätzlich möglich sein.

Aktuell ist das Verhalten gleich mit dem Verhalten aus der alten Anwendung.
