### ISSUE TITLE
Anwendung ohne CAS starten.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#63]
Das WFC erstellt beim starten eine Anfrage an das CAS.
Wenn diese Anfrage fehl schlägt, stürtzt die Anwendung ab bzw. kommt nicht weiter.

Wir wollen das sich die Anwendung öffnet und im Nachhinein die Verbindung wieder aufgebaut wird (wenn bspw. das WLAN beim Starten weg war.).

**Comment by CE7** [comment]
Eventuell sollten wir die TimeOutException auch interpretiert werden. Der Benutzer sollte darauf hingewiesen werden, dass der Server nicht verfügbar ist.
Erstellung einer aussagekräftigen Fehlermeldung für den User:
* Internetverbindung nicht da
* Falsches Passwort
* ....

**Comment by janiak-minova** [comment]
Wird mit #440 behandelt.
