### ISSUE TITLE
Selektionskriterien speichern

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#67]
Wir möchten die Selektionskriterien speichern. Dazu gehört:
* Werte der Suchtabelle
* Spaltenbreite und -Reihenfolge (Suche, Index)
* Standard-Kriterien, die beim Start automatisch geladen werden
* mehrere Kriterien, die man beim Speichern und Laden auswählen kann

Wir sollten das noch konzeptionell absprechen, ob Spaltenbreite und -Reihenfolge (Suche, Index) mit dazu gehören oder ob diese auf andere Weise persistiert werden sollen.

**Comment by janiak-minova** [comment]
Siehe #386.
