### ISSUE TITLE
Verhalten des Verwerfen-Buttons

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.rcp#670]
Beim Testen ist aufgefallen, dass der Verwerfen-Button sich etwas unerwartet verhält.

Wenn man einen Eintrag aus der Liste links wählt, wird er rechts in den Detailsbereich geladen.
Klickt man dann auf "Neu" wird der Detailsbereich auch geleert, klickt man dann aber auf "Verwerfen" lädt es den zuletzt selektierten Eintrag wieder rein, aber als neuer Eintrag. (Wenn man auf Speichern klickt, kommt die Warnung, dass bereits ein Eintrag existiert.)

Selbes Verhalten, wenn man statt "Neu" auf "Löschen" klickt und dann wieder auf "Verwerfen". Die gerade gelöschten Daten werden wieder recht in den Detailsbereich geladen.

Wenn man gerade dabei ist ein neues Detail auszufüllen und dann auf "Verwerfen" klickt, werden auch die Daten des vorher angeklickten Eintrags geladen.

Ist das so gewollt?

**Comment by wis36** [comment]
Bisher (11) ist der Sinn des Verwerfen-Buttons, dass nicht gespeicherte Änderungen, die der Nutzer an dem Detail-Datensatz gemacht hat, wieder verworfen werden. Dazu speichern wir uns für jedes Feld nicht nur einen value, sondern noch einen oldValue. Diesen könnte man dann wiederherstellen. Tatsächlich wird aber der Datensatz neu aus der Datenbank gelesen.

Bei einem neuen Datensatz wäre es sinnvoller, nochmal auf "Neu" zu drücken, wenn man noch mal neu anfangen möchte. Funktionalität wäre sowieso dasselbe. Deshalb hatte ich in der 11er Anwendung für neue Datensätze den "Verwerfen"-Button deaktiviert.

Vielleicht habt ihr für Stand 12 auch eine andere Definition. Ich denke aber nicht, dass ein gelöschter oder "der vorher angezeigte" Datensatz erscheinen soll.

**Comment by janiak-minova** [comment]
Mit Pullrequest #701 ändert sich das Verhalten.
Wenn ein Eintrag im Index ausgewählt wird, werden die Informationen Zwischengespeichert.
Beim Klicken auf den Verwerfen-Button werden diese Daten dann wieder ins Detail geladen. 
Wird das Detail geleert (durch Speichern, neues Detail erstellen, oder Löschen) werden auch die zwischengespeicherten Daten verworfen. Klickt man jetzt auf Verwerfen passiert nichts. 
Entsprechend sollte der Button deaktiviert werden, wenn er keinen Effekt hat.
