### ISSUE TITLE
CSS implementieren

### ISSUE THREAD

**Issue by ingraban** [minova-afis/aero.minova.rcp#68]
Wir möchten die Anwendung vollständig über CSS gestalten können.
Dazu müssen wir zum Einen CSS  aktivieren und danach auch noch verschiedene CSS-Themes anbieten. 
Dabei sind auch die Plattformen zu berücksichtigen.

Das aktive Theme muss in den Preferences ausgewählt und eingestellt werden können.

**Comment by janiak-minova** [comment]
Schriftgrößen können inzwischen über die Einstellungen angepasst werden.
Für alles andere brauchen wir ein präziseres Ticket (ERC).
