### ISSUE TITLE
Plugins Nachladen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#680]
Um die Anwendung ausliefern zu können, müssen Plugins nachgeladen werden können. 
Ein Beispiel ist der Workingtimehelper für die Stundenerfassung.

Es ist schon möglich, Daten vom CAS herunterzuladen bzw. zu aktualisieren (z.B. die Übersetzungen). 
Die Schwierigkeit ist es, die heruntergeladenen Plugins zu installieren.
Wie in #236 erwähnt, läuft das Installieren über die p2 API.

**Comment by CE7** [comment]
im alten Code wird mit Hilfe der Klasse **MinovaPluginActivator.java** ein oder mehere Plugins aus dem Ordner: plugins geladen:

**Comment by vogella** [comment]
WFCDetailPart - Line 257 lädt dynamisch die Klasse

Vorbereitung: 

- Entfernen der Helper aus dem Feature (aero.minova.workingtime.helper)

1.) Plug-in herunterladen von /plugins Folder im neuen aero.minova.rcp.dataservice.internal.PluginDownloadService
2.)
