### ISSUE TITLE
Keine Vorschlagsliste sichtbar.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#684]
Mit der neuesten Version von WFC ist die Vorschlagsliste bei Eingabefeldern mit Drop-Down-Menüs
nicht mehr sichtbar.
Die Vorschläge sind aber vorhanden, da die Vervollständigung über Tab funktioniert.

https://user-images.githubusercontent.com/7956931/123986234-6d927980-d9c6-11eb-9b51-4fcd349e84c4.mp4

**Comment by wis36** [comment]
Dieses Problem habe ich schon länger, ich hatte vor kurzem mit David darüber gesprochen.

Es liegt daran, dass in den Lookup-Feldern ein "writtenText" ist, der nicht gelöscht wird.

Es tritt auf, wenn
* ein Ticket mit unvollständigen Informationen geladen wird
* der Wert aus dem Lookup gelöscht wird (DEL)

Wir hatten mal auf einem Branch beim Löschen writtenText ebenfalls gelöscht, das war schon mal hilfreich. Beim Laden von Tickets müsste man auch darauf achten.

Oder generell den sichtbaren Wert mit dem im Hintergrund synchron halten.

**Comment by wis36** [comment]
Ein weiterer Effekt ist übrigens, dass die jeweiligen Lookups zwar orange markiert sind, aber mit Enter nicht als Pflichtfeld angesprungen werden (lt. `writtenText` sind sie ja nicht leer)

**Comment by splitcells** [comment]
Wir haben es heute nochmals probiert.
Wir konnte das Problem aber nicht nachvollziehen.

**Comment by wis36** [comment]
Beispiel: Ticket #52327 hat keinen Aufwand

**Comment by janiak-minova** [comment]
Was genau machst du, damit die Vorschläge nicht auftauchen? Und hast du die aktuelle Version (20.0.22)?

**Comment by wis36** [comment]
Ich habe die aktuelle Version (aktuellen Stand master).

**Comment by wis36** [comment]
So direkt konnte ich es nicht mehr nachstellen. Jetzt ist es wieder passiert. Beim Debuggen konnte ich nur feststellen, dass das Fensterchen nur angezeigt wird, wenn das dazu passende Textfeld den Focus hat. Dann kann ich aber auch nur dann auf den Pfeil neben dem Textfeld klicken, sonst passiert nichts.

**Comment by wis36** [comment]
Wenn das Fensterchen erzeugt wird, wird es zwar angezeigt, aber man kann es nicht sehen, es ist wahrscheinlich im Hintergrund.

**Comment by wis36** [comment]
So kann man es sehen:
![grafik](https://user-images.githubusercontent.com/20420949/124123943-22d13a00-da78-11eb-837d-3816f8e00410.png)

**Comment by wis36** [comment]
Wenn ich auf den Pfeil von "Aufwand" klicke, geht kein Fenster auf.

Dasselbe Verhalten verhindert auch das Aufklappen, wenn zwar kein sichtbarer Wert vorhanden ist, aber in `writtenText` etwas steht (z. B. ZPROGRAM).

**Comment by wis36** [comment]
Also eigentlich 2 Probleme:
1. der angezeigte Wert sollte immer synchron mit dem Daten-Wert sein (außer wenn man gerade tippt) - mMn sollte sich darum der `LookupContentProvider` kümmern
2. die Vorschläge sollten im Vordergrund geöffnet werden

**Comment by wis36** [comment]
Das Problem mit dem Pflichtfeld (s. o.) würde sich dadurch automatisch mit lösen.

**Comment by splitcells** [comment]
Das Problem taucht beim mir zur Zeit regelmäßig auf.

**Comment by splitcells** [comment]
Falls wir jemals Windows-Nutzer bei einem Kunden haben werden,
wird dieser Fehler sofort aufkommen.

**Comment by Bauer-David** [comment]
Ich habe den Fehler wahrscheinlich beseitigt, dass muss aber noch getestet werden, da er ziemlich sporadisch auftaucht. Daher habe ich Martins eine Version mit der Fehlerlösung bereitgestellt, dass diese von ihm über ein paar Tage getestet wird.

**Comment by wis36** [comment]
Ich bin jetzt auf dem Branch `#684` wie David empfohlen hatte, es tritt aber immer noch auf.

Hängt wahrscheinlich mit #859 zusammen.

**Comment by wis36** [comment]
Es tritt auch beim "normalen" Textassist auf, nicht nur beim Lookup:

![grafik](https://user-images.githubusercontent.com/20420949/140722328-a586ae4b-df5b-4758-9225-9072031de791.png)

**Comment by Bauer-David** [comment]
Ich habe das Problem bei Nebula in einem Issue geschildert. Falls es Fortschritte gibt schriebe ich sie hier nochmal rein.

Issue [#419](https://github.com/eclipse/nebula/issues/419) bei Nebula.

**Comment by Bauer-David** [comment]
Ein Entwickler von Nebula hat eine mögliche Lösung bereitgestellt. Diese wird von @wis36 getestet. Sobald wir wissen, dass die Lösung funktioniert, erstelle ich ein Pull Request für das Nebula Projekt. Momentan habe ich nur unsere Lookups korrigiert. Heißt unter Windows kann es bei den TextAssists noch zu dem Fehler kommen.

**Comment by wis36** [comment]
Ich habe vorhin auf den Branch `#684` gewechselt.

Ist trotzdem gerade wieder aufgetreten, sowohl im Lookup als auch beim Datum.

**Comment by Bauer-David** [comment]
In der Stundenerfassung unter Windows wird die Headsection für Enter ignoriert.

Beispiel:
(EnterSelectsFirstRequired = true)
Betätigen von Enter in dem Feld "Kontrakt" --> Springt ins Feld "Bis" und überspringt andere leere Pflichtfelder
Betätigen von Enter in dem Feld "Bis" --> Selektion beleibt auf "Bis"

**Comment by wis36** [comment]
Wenn ich WFC neu öffne, funktioniert es noch. Ich gebe unten Daten ein, drücke Enter und es springt in ein Pflicht-Lookup.

Ich glaube, dafür gab es ein anderes Issue. Liegt wahrscheinlich am writtenText.

**Comment by wis36** [comment]
Ich habe in drei Lookups manuell Werte eingegeben. Das 4. wurde automatisch ausgefüllt, weil es nur noch eine Möglichkeit gab.

Die drei Lookups können jetzt nicht mehr mit Enter angesprungen werden, das 4. funktioniert!

**Comment by wis36** [comment]
Alle Lookups, in die ich manuell einen Wert eingegeben habe - ein Lookup-Wert oder eine Ticketnummer - werden nicht mehr angesprungen.

**Comment by Bauer-David** [comment]
Stand 02.02.2022

Projekt wird von BAD an einen Mitarbeiter übergeben, der nativ mit Windows arbeitet.

Das Issue im GitHub des Nebula Projektes wurde aktualisiert und es wurde dort um weitere Hilfe gebeten.

**Comment by wis36** [comment]
Ich habe den Branch den Lea bereitgestellt hat und lade nebula aus dem Workspace (master vom minova-github).

Im LookupComposite stand in Zeile 241 nur
`popup.setVisible(true);`

und NICHT der Bugfix-Versuch
`popup.setActive();`

Ich habe die Zeile jetzt eingefügt. Leider konnte mein Eclipse an dieser Stelle kein Hot-Code-Replace machen. Ich muss also noch ein paar Tage testen, ob es jetzt wieder auftritt oder nicht.

**Comment by wis36** [comment]
Genauer gesagt habe ich die Stelle so geändert:

```
		if (!popup.isVisible()) {
			popup.setActive();
			popup.setVisible(true);
		}
```

**Comment by wis36** [comment]
Gestern nachmittag ist es trotzdem wieder aufgetreten. Diesmal habe ich auch die "normalen" Eingabefelder ausprobiert (Uhrzeit). Auch hier erscheint der Tooltipp im Hintergrund ("conversion error" oder so ähnlich).

**Comment by wis36** [comment]
Hm, tritt trotzdem wieder auf.

Der Bugfix-Versuch war auch im TextAssist NICHT drin.

Diesmal funktioniert Hot-Code-Replace aber.

An beiden Stellen funktioniert der o. g. nicht. Es verhält sich genau wie vorher.
Solange das popup unsichtbar ist, macht `setActive()` nichts.

**Comment by wis36** [comment]
Wenn ich es umdrehe, funktioniert es auch nicht wie gewünscht:

```
		if (!popup.isVisible()) {
			popup.setVisible(true);
			popup.setActive();
		}
```

Jetzt bekommt es den Focus, das ist auch nicht gewünscht, weil man dann nicht weiter tippen kann.

**Comment by wis36** [comment]
Man sieht es auch in der Klasse, dass `setActive()` nur für sichtbare Objekte funktioniert:
```
public void setActive () {
	checkWidget ();
	if (!isVisible ()) return;
...
}
```

**Comment by wis36** [comment]
Vielleicht könnte man mal probieren:
* `forceActive()`
* `open()`
* ShellListener überprüfen?

**Comment by wis36** [comment]
Ich versuche es jetzt mit `moveAbove (Control control)`.

**Comment by wis36** [comment]
Hat auch nicht geholfen. Ich habe `moveAbove(this)` und `moveAbove(getParent())` probiert.

**Comment by wis36** [comment]
Was allerdings hilft, ist `popup.moveAbove(getShell());`
