### ISSUE TITLE
Zeiten im Index werden nicht sortiert

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#686]
Wenn Stunden nicht direkt nach einander erfasst werden, werden sie nicht sortiert.

Beispiel:
Man erfasst zuerst die Stunden 08:00 - 09:30 dann 09:30 - 11:00. Dann fällt einem ein, dass man zwischen 09:00 und 10:00 Uhr was anderes gemacht hat. Man verkürzt die erfassten Stunden und fügt dann noch 09:00 bis 10:00 Uhr ein. Danach ist die Ausgabe im Index wie folgt:

08:00 - 09:00
10:00 - 11:00
09:00 - 10:00

Der Index sollte die Werte nach Zeit sortieren.

**Comment by janiak-minova** [comment]
Die Datensätze sind in der Reihenfolge, wie sie Eingefügt wurden. Wenn eine Sortierung nach Uhrzeit gewünscht ist, kann das über die Spaltensortierung umgesetzt werden.
