### ISSUE TITLE
Datumsformat in Stundenerfassung falsch: Französisch

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#688]
![Bildschirmfoto 2021-07-02 um 07 29 35](https://user-images.githubusercontent.com/20420898/124225219-5909ca80-db07-11eb-8470-de36fcfb20cf.png)

Hier sollte in der Regel ein Datumsfeld nicht mit Buchstaben angezeigt werden!

**Comment by Bauer-David** [comment]
Das Pattern für die Formatierung kann nun vom Benutzer selbst bestimmt werden. Wenn keins angegeben ist wird folgendes verwendet:

Für das Datum gilt: FormatStyle.MEDIUM
Für die Zeit gilt: FormatStyle.SHORT
