### ISSUE TITLE
DetailPart Resize Icon passt nicht

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#705]
Das Icon des Resize Buttons im DetailPart soll geändert werden, da der Button eine andere Funktionalität hat wie die im Index und SearchPart. Es soll das Icon genutzt werden, bei dem die Pfeile in die vier Ecken zeigen.

**Comment by wis36** [comment]
Eigentlich wäre es sinnvoller andersrum.
Im DetailPart wird nur eine vertikale Anpassung gemacht, also nur zwei Richtungen.
Im Search- und IndexPart werden die Zeilenhöhen und Spaltenbreiten der NatTable angepasst, also 4 Richtungen.

**Comment by Bauer-David** [comment]
Wir verwenden das Icon nicht wegen der Funktionalität, sondern zur visuellen Trennung. Der Resize Button im Detail passt die Größe der Anwendung an und die Resize Button im Index und Search Part die Tabellen. Es soll eine klarer unterschied zwischen diesen sichtbar sein. Daher ist es auch ein anderes KeyBinding, dass in der gesamten Anwendung ansprechbar ist und nicht nur im jeweiligen Part.

**Comment by wis36** [comment]
Wenn man die Icons tauscht, haben wir beides 😁
