### ISSUE TITLE
Testumgebung SIS (OilTanking) erstellen

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#708]
Wir brauchen ein Testsystem damit wir alle Anforderungen von Oil Tanking abbilden können. 

- [x] eigenen Server konfigurieren (@splitcells )
- [x] CAS für Oil Tanking aufsetzen (@splitcells , @weber-minova)
- [x] Alle Masken, OPs, Helperklassen, Icons raussuchen und in Testsytem eintragen (@OlliDob)
- [ ] XBS konfigurerien application.xbs oder Aus der Datenbank laden!?

**Comment by OlliDob** [comment]
Im Minova-git gibt es ein Kundenprojekt für SIS bei Oiltanking: de.minova.oiltanking.swb.

Dort stehen die Abhängigkeiten in der Setup.xml bzw. der pom.xml.

**Comment by splitcells** [comment]
Werde ich angehen, wenn Kerstin wieder da ist.

**Comment by weber-minova** [comment]
CAS läuft. Passwort und Nutzername sind im KeePass unter 'Oiltanking Test CAS User'

**Comment by splitcells** [comment]
Können wir dieses Ticket schliessen?

**Comment by janiak-minova** [comment]
Letzter Punkt wird mit #693 geklärt.
