### ISSUE TITLE
Text in Einstellungen wird teilweise nicht umgebrochen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#724]
In den Einstellungen unter "Anwendung" gibt es einen Textblock, der automatisch umgebrochen wird.

<img width="799" alt="Bildschirmfoto 2021-07-21 um 10 31 12" src="https://user-images.githubusercontent.com/77741125/126457587-d337ed8b-d2df-4465-8d2f-3015950d70ce.png">

Dieses Verhalten sollte für alle Texte gelten. Für die Beschreibung an Checkboxen ist das aktuell nicht der Fall:

<img width="545" alt="Bildschirmfoto 2021-07-21 um 10 32 21" src="https://user-images.githubusercontent.com/77741125/126457748-f2737ca7-0c57-416f-b926-9728403eac49.png">

**Comment by Bauer-David** [comment]
Wir haben uns damals dafür entschieden, dass der Text von Checkboxen nicht umgebrochen wird, sondern ein kürzerer Text eingesetzt wird und die Beschreibung und einem eigenen Beschreibungslabel darunter eingefügt wird.
