### ISSUE TITLE
Passwörter mit Umlauten funktionieren nicht

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#743]
Man kann sich in der WFC-Anwendung nicht anmelden, wenn das Passwort einen Umlaut enthält.

**Comment by weber-minova** [comment]
Wenn ich über die WFC-Anwendung mich beim CAS anmelden möchte, kommt es so an:
<img width="81" alt="Bildschirmfoto 2021-07-29 um 08 13 35" src="https://user-images.githubusercontent.com/75690564/127441369-3aa91bd9-d7b2-4621-a047-aabd4df50774.png">

Wenn ich über Postman eine Anfrage schicke, würde der Umlaut angezeigt werden.

**Comment by theuerer** [comment]
Ohne das "ö" funktioniert die Anmeldung wieder bei mir

**Comment by janiak-minova** [comment]
Wir haben noch keine Lösung gefunden, Lars hat auf Stackoverflow geposted:
https://stackoverflow.com/questions/69012993/java-11-httpclient-authenticator-with-umlaute

**Comment by janiak-minova** [comment]
User und Passwort werden jetzt mit ISO-8859-1 encodiert. Mit Java 11 ist eine utf-8 Codierung nicht möglich, dafür müsste unsere Javaversion erhöht und auch der Server angepasst werden.
