### ISSUE TITLE
Dynamische Werte aus Masken auswerten

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#757]
In einigen Masken sind Knöpfe und Felder mit 
`<dynamic property="...">...</dynamic>`
definiert.

Diese dynamischen properties müssen ausgelesen und umgesetzt werden können.

Soll JavaScript für die Auswertung genutzt werden: #776

**Comment by wis36** [comment]
Doku für dynamic Stand 10/11 gibt es hier:
https://trac.minova.com/trac/minova/wiki/ISO/develop/RCP/ScriptEngine

**Comment by CE7** [comment]
wird in #803 dokumentiert, und damit für jede betroffene Maske / Optionpage separat gelöst. Es braucht dann einen entsprechenden Helper.
