### ISSUE TITLE
wiederkehrender Fehler, nach Problem mit Ticket

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#761]
Wenn ein Ticket nicht aufgelöst werden konnte, bekommt man eine entsprechende Meldung (aber mit UTF8-Problem).

Schlimmer ist allerdings, dass danach jedesmal diese Meldung kommt, wenn man irgendwas neues eingibt (auch gültige Daten):

![grafik](https://user-images.githubusercontent.com/20420949/127666087-9bb2f402-a8d2-46f0-9f9d-aab36225c0fe.png)

**Comment by janiak-minova** [comment]
Was genau gibst du ein, damit du den Fehler bekommst?

**Comment by wis36** [comment]
Ein Ticket, das nicht aufgelöst werden kann, also irgendeins das es nicht gibt. Vielleicht #7
