### ISSUE TITLE
"Size" Attribut von Spalten auswerten

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#765]
In einigen Masken (z.B. CTSTestTermin auf Publictest) sind einige Spalten in der index-view mit dem `size="0"` Attribut versehen. Dieses Attribut muss noch ausgewertet. Für den Fall `size="0"` sollte die entsprechende Spalte gar nicht angezeigt werden.

**Comment by wis36** [comment]
Außerdem gibt es auch `visible="false"`, was dasselbe bewirkt.

Bis Stand 10 wurde der Wert von `size` (falls >0) auch für die Breite der Spalte verwendet. Im Stand 11 habe ich das nicht mehr implementiert. Wird wohl auch selten verwendet.
