### ISSUE TITLE
Knöpfe wirken wie deaktiviert.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#769]
Der Grauton der Schrift erzeugt manchmal die Illusion,
dass die Knöpfe deaktiviert sind (vielleicht liegt es nur an mir).

Zudem denke ich, dass für einige Nutzer die graue Schrift auf grauen Hintergrund ein Problem sein wird.
Im AFIS hat man bspw. auch angemerkt,
dass der Hintegrund bei gedrückten Filterknöpfen nicht deutlich genug ist,
da sie die Anwendung in der Sonne verwenden.

Man könnte vielleicht Deutsche Richtlinien als Hilfe nehmen: https://www.barrierefreies-webdesign.de/richtlinien/wcag-2.1/erfolgskriterien/kontrast-minimum.html

Vielleicht liegt es aber auch an meinen Augen ^^

![grafik](https://user-images.githubusercontent.com/7956931/127979233-db736782-d2c9-41b0-abff-ce36b359fbea.png)

![grafik](https://user-images.githubusercontent.com/7956931/127979879-36ffd24c-7180-4f24-b945-573fdf484387.png)

**Comment by wis36** [comment]
Meine Augen empfinden die Buttons auch als deaktiviert.

**Comment by janiak-minova** [comment]
Aktuell wird für die Farbe der Buttons das Standartverhalten des jeweiligen Betriebssystems genutzt. Unter Windows ist das für die Farbe eben diese grau, was wie deaktiviert wirkt. 

Leider scheint es nicht möglich zu sein, in einer RCP-Anwendung die verschiedenen Button-Typen (Push, Check, ...) seperat über css zu stylen.
Wenn die Hintergrundfarbe für Buttons auf weiß geändert wird, sehen die Knöpfe zwar nicht mehr deaktiviert aus, es sind aber auch die Checkboxen betroffen:
<img width="704" alt="Bildschirmfoto 2021-08-30 um 12 17 54" src="https://user-images.githubusercontent.com/77741125/131325012-a6440c75-a271-4ed4-a8ea-b0caf8b410ed.png">

**Comment by splitcells** [comment]
Mir scheint als wäre der Text auch auf grau gesetzt.
Wäre es möglich nur die Schriftfarbe anzupassen?

**Comment by janiak-minova** [comment]
Text wird mit #833 insgesamt dunkler und damit hoffentlich besser lesbar.

**Comment by janiak-minova** [comment]
Buttons können doch seperat gestyled werden:

```
Button[style~='SWT.PUSH'] {
	color: #222222;
	background-color: white;
}
```

**Comment by janiak-minova** [comment]
Wir haben entschieden, dass die Textfarbe dunkler wird (siehe Screenshot), aber die Hintergrundfarbe der Buttons weiter OS-Abhänging und damit auf Windows grau bleibt.
