### ISSUE TITLE
JobExecuter (manuell) anstoßen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#774]
Aus der Anwendung muss der JobExecuter angestoßen werden können, damit dieser dann seine Aufgaben ausführt.

Beispieljob: `ch.minova.job.xmlinvoiceexport`.

Es soll eine Möglichkeit geben, die Jobs manuell ausführen zu können.
Ob das über einen SuperUser-Modus funktioniert oder z.B. über Rechte ist noch zu klären.

Zugehöriges Issue für CAS: minova-afis/aero.minova.core.application.system#170

**Comment by janiak-minova** [comment]
Beispiel manuelle Aktivierung in der 11er Anwendung:
SuperUser Modus 

<img width="646" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/77741125/127990357-74ebe2d6-9fd3-4021-a21e-131082e26298.png">

**Comment by CE7** [comment]
Hier streben wir eine Lösung über PlugIns an. Man kann diese PlugIns dann viel besser testen.
Damit würde auch das Nutzen von Java-Script nicht mehr nötig sein.

**Comment by CE7** [comment]
- [ ] Welche Jobs werden verwendet ? 
- [ ] Monatsabschluss? 
- [ ] Daten importieren, exportieren?

SAW: Aufruf einer Prozedur mit Parameter and en CAS.
Dann wird der CAS entscheiden müssen wie es weiter verarbeitet wird. Der Aufruf ist gleich zu den anderen Aufrufen
