### ISSUE TITLE
Grids je nach Konfiguration immer vollständig anzeigen

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#777]
Wir benötigen eine Option in den Masken / optionpages, um programmatisch zu entscheiden, ob das Grid automatisch mit allen Spalten angezeigt wird. 

Dies ist ein Wunsch vom Kunden Oiltanking

**Comment by janiak-minova** [comment]
Maske ServiceContract normal:
<img width="1918" alt="Bildschirmfoto 2021-08-03 um 12 13 36" src="https://user-images.githubusercontent.com/77741125/127999067-76661b84-d64d-4ec9-8508-cc280f0358ac.png">

Gridbreite optimiert:
<img width="1918" alt="Bildschirmfoto 2021-08-03 um 12 13 23" src="https://user-images.githubusercontent.com/77741125/127999037-3ee25165-f5a7-4af9-90fb-1135f926d410.png">

**Comment by CE7** [comment]
Hier sollten wir die Breite der OPs speichern und beim Schließen muss die Breite gespeichert werden.

**Comment by wis36** [comment]
Wie viele Spalten man sehen kann, ist ja von der darstellbaren Größe abhängig... der blaue Doppelpfeil links/rechts erscheint im SIS11, wenn `<grid fill="auto">` definiert ist.

**Comment by CE7** [comment]
Es wird keine Eigenschaft <grid fill="auto"> geben. Die Anwendung soll die Größe speichern, die der Benutzer einmalig festgelegt hat pro Maske

**Comment by CE7** [comment]
Hier sollte die Breite sich direkt an den Detail-Bereich anpassen können. Somit muss der Benutzer die Breite des Details vergrößern um dann alle Spalten anzeigen zu können.

**Comment by janiak-minova** [comment]
Das Persistieren wird mit #804 behandelt.
