### ISSUE TITLE
Methode für Stundenerfassungs-Tickets auswerten in WorkingtimeHelper verschieben

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#783]
Aktuell befinden sich einige Methoden, die für das  Stundenerfassungs-Ticket auswerten verantwortlich sind in der Klasse `WFCDetailCASRequestUtil`. Dies ist eine allgemeine Klassen, deshalb sollten die Methoden in den WorkingtimeHelper verschoben werden.

Offene Frage:
Ist die Anfrage eines Tickets über `#...` eine allgemeine Funktion, oder gibt es Tickets nur in der Stundenerfassung?

**Comment by wis36** [comment]
Bisher nur Stundenerfassung.

Ich weiß aber nicht ob noch was geplant ist 😉
