### ISSUE TITLE
Zeit und Datumsfelder unter Linux nicht nutzbar

### ISSUE THREAD

**Issue by kos366** [minova-afis/aero.minova.rcp#791]
Beginnt man in einem Zeit oder Datumsfeld eine Eingabe dann bleibt man immer im ersten Feld der Eingabe hängen, also beim Datum beim Tag und bei der Zeit bei der Stunde. Manuelles platzieren des Cursors schafft keine Abhilfe.

![grafik](https://user-images.githubusercontent.com/20420811/129539717-1724b36a-f922-4bf8-b5ac-5af7167e078d.png)

Einzige Möglichkeit ist auch hier den Text aus der Zwischenablage in das Zeit- bzw Datumsfeld zu kopieren.

Ist wahrscheinlich ein ähnliches Fokusproblem wie #790

**Comment by kos366** [comment]
Nach langen Versuchen war die einzige gefundene Lösung beim Fokuserhalt ein leerzeichen in das feld schreiben zu lassen. Dann wird dieses verschluckt und das erste vom Benutzer eingegebene Zeichen wird verarbeitet. 

Workaround in a2d7ccdd

**Comment by kos366** [comment]
Startet man die Anwendung aus dem eclipse, dann funktioniert der Workaround ziemlich gut. Startet man die gebaute Anwendung funktioniert die Eingabe gar nicht mehr.

**Comment by kos366** [comment]
Nächster Workaround ist die TextAssist Felder unter Linux durch einfache Text Felder zu ersetzen, 072d28a9

Die sich ergebenden Werte kann man als Tooltip anzeigen, 71ee439e

Auch diese Lösung ist nicht optimal, da der Tooltip immer an der Maus angezeigt wird und nicht am Feld und da das Look and Feel natürlich so ein anderes ist als unter Windows und MacOs.

**Comment by kos366** [comment]
Der Tooltip sollte auch wieder verschwinden können f9361233

**Comment by kos366** [comment]
2f23a4c5 und d80fd05b aus hom-testassist-linux  sollten wir dann mal duch einen pull-request mit dem master zusammenführen

**Comment by janiak-minova** [comment]
Ich habe Pullrequest #1177 mit den beiden commits erstellt und dieses Issue sowie #790 verlinkt. Wenn damit TextAssist und Lookups unter Linux funktionieren können wir das mergen und die beiden Issues schließen.

**Comment by kos366** [comment]
Die Lookups funktionieren mit kleinen Einschränkungen im Timing, besser bekomme ich es nicht hin.

Die Zeit und Datumsfelder funktionieren mit normalen Textfeldern und Tooltips. Ist aktuell eine gute Übergangslösung, vielleicht funktioniert das TextAssist ja irgendwann mal korrekt mit Linux.

Probier bitte noch, das meine Änderungen keine negativen Auswirkungen für MacOs und Windows haben.
