### ISSUE TITLE
Datumsänderungen im Suchenbereich werden ignoriert

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#798]
Beschreibung von Gudrun aus Ticket [#7](https://github.com/minova-afis/aero.minova.workingtime/issues/7) in aero.minova.workingtime
Ich habe nach allen Datensätzen gesucht die >= 010119 sind. Das hat funktioniert. Dann habe ich die letzten 2 Stellen des Datums (Jahr) überschrieben. Das SIS hat nicht neu gefiltert.

**Comment by Bauer-David** [comment]
Im Index werden nur maximal die Daten von den letzten 40 Tagen angezeigt.

**Comment by Bauer-David** [comment]
Soll die Speere von 40 Tagen aufgehoben werden, bzw unter bestimmten Bedingungen aufgehoben werden?

**Comment by ingraban** [comment]
Habe gerade mit Gudrun gesprochen. Sie hat kein Problem mit der Beschränkung auf die letzten 40 Tage. Prinzipiell werden die Daten nicht aktualisiert, wenn man nur den Wert innerhalb der Abfrage ändert.

**Comment by Bauer-David** [comment]
Die 40 Tage Begrenzung bleibt erhalten. Es bestand kein Fehler, da die Daten für die beiden eingegebenen Suchkriterien die selben waren. 

Beispiel von Gudrun:
Suchkriterium => Datum = 010119
Ausgabe => Daten der letzten 40 Tage

geändertes Suchkriterium => Datum = 0101
Ausgabe => Daten der letzten 40 Tage

In beiden Fällen liegt das angegebene Datum weiter als 40 Tage zurück. Daher ist die Ausgabe identisch.
