### ISSUE TITLE
Welche Jobs brauchen wir im SIS?

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#806]
- [ ] Welche Jobs werden verwendet ? 
- [ ] Monatsabschluss? 
- [ ] Daten importieren, exportieren?
- [x] SQL2FILE

SAW: Aufruf einer Prozedur mit Parameter and en CAS.
Dann wird der CAS entscheiden müssen wie es weiter verarbeitet wird. Der Aufruf ist gleich zu den anderen Aufrufen

**Comment by OlliDob** [comment]
* Es sollen Daten per Webservice an SAP übertragen werden.
* Emailversand
* BIRT Repots für die Rechnung
* ggf. XML-Reports

**Comment by CE7** [comment]
Wir brauchen die genauen Jobs, damit wir entsprechende umziehen können. 
Was ist mit Tagesabschluss,  Monatsabschluss, Jahresabschluss?

**Comment by OlliDob** [comment]
Das wird ein neuer Job, den es noch nicht gibt.

Aktuell sind keine Tages-, Monats- und Jahresabschlüsse vorgesehen.

**Comment by STKLEBA** [comment]
Habe gerade nochmal kurz mir Gudrun gesprochen, um zu verhindern, dass Jorunalsätze mit alten Monaten abgerechnet werden können, soll zumindest ein Monatsabschluss möglich sein, Tagesabschlüsse sind wohl nicht nowending

**Comment by janiak-minova** [comment]
Den SQL2File brauchen wir zumindest auf Anwendungsseite vorerst nicht, da das direkt über die Prozedur läuft.

**Comment by STKLEBA** [comment]
Nach Rücksprache mit Olli und Martins funktioniert alles soweit ohne Jobs bis auf XML Reports und Tages bzw. Monatsabschlüsse. Hier ist von meiner Seite final zu klären ob wir Tages und Monatsabschlüsse brauchen und ob hierbei auch XML-Reports wie Tageslisten und Ähnliches generiert werden sollen
