### ISSUE TITLE
Datums-/Zeitformat konsistent Nutzen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#829]
Das Datums- und Zeitformat, das in den Einstellungen gesetzt wurde, muss konsistent in der ganzen Anwendung genutzt werden. Aktuell ist es nur in Feldern.

- [ ]  Nattables (Suche, Index, Grids) 
<img width="1553" alt="Bildschirmfoto 2021-08-27 um 12 12 20" src="https://user-images.githubusercontent.com/77741125/131111602-c52271fd-a39a-414e-afb8-f24fc71d7271.png">

- [x] Hint in leeren Datums-/Zeitfeldern
<img width="132" alt="Bildschirmfoto 2021-08-27 um 12 16 52" src="https://user-images.githubusercontent.com/77741125/131112191-30902539-6870-49e1-aeea-7918bce8f1c8.png">

**Comment by Bauer-David** [comment]
Die NatTables werden in einem eigenen Issue behandelt. #871
