### ISSUE TITLE
Persitieren der UI

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#848]
Beim Starten der Anwendung sollte die UI genau so sein, wie sie beim letzten Mal geschlossen wurde. 
Dafür wird bei Änderungen für die Darstellung der OPs, Grids in OPs, Index, Suche immer gespeichert. Dies wird dann in einer eigenen Preferenz abgelegt (zum Beispiel: "LAST_STATE")
Die Suchkriterien sollten dann auch so geladen werden. 

Der Anwender bekommt mein Starten ein Popop angezeigt!
"Der letzte Zustand der Anwendung wird geladen! Wenn Sie dies nicht möchten, laden Sie den Standard manuell! (Suchkriterien Laden Knopf)
[ ] Diesen Hinweis nicht nochmal anzeigen!" 

- [x] Persistieren der Suchtabelle inkl. Einträgen
- [x] Persistieren der Indextabelle (NICHT der Zeilen)
- [x] Persistieren der Grid-Tabellen (NICHT der Zeilen)
- [x] Popup mit "Hinweis nicht erneut zeigen" Checkbox

**Comment by janiak-minova** [comment]
Der Dialog wird beim Starten der Anwendung angezeigt, NICHT wenn eine neue Perspektive geöffnet wird.


<img width="684" alt="Bildschirmfoto 2021-09-15 um 10 39 23" src="https://user-images.githubusercontent.com/77741125/133401028-f01b4ea9-477a-4075-95f9-34af174ec343.png">

Wenn die Checkbox einmal markiert wurde muss die entsprechende Datei/Zeile in der Datei per Hand gelöscht werden, damit die Nachricht wieder erscheint. 
Sie liegt in `<workspace Ordner>/.metadata/.plugins/org.eclipse.core.runtime/.settings/aero.minova.rcp.rcp.prefs` unter `NeverShowRestoringUIMessage`.
