### ISSUE TITLE
sql-index in Aufrufen für Prozeduren berücksichtigen

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#855]
Der SQL-Index spielt eine Rolle wenn Prozeduren aus der Anwendung aufgerufen werden sollen. Die Reihenfolge bestimmt die Reihenfolge der Felder in der Prozedur.

**Comment by CE7** [comment]
Da dieses Feld aktuell nicht Pflicht ist, könnte man es auch weglassen. Hier funktioniert allerdings aktuell dann nur das vollständige "weglassen" des Feldes. Ich bin der Meinung, dass wir hier davon ausgehen können, dass es immer da ist. 
Sollte es dann fehlen, müssen wir die Maske entsprechend anpassen! Hier muss das Schema erweitert werden.

**Comment by CE7** [comment]
Wir bekommen Probleme, wenn man Ihn nicht vollständig füllt. Zum Beipsiel: 

1,2,3,4,5,null1,null2,null3,null4,10
aktuell ist es definiert bei keinem Vorkommen dass wir BigInter = -1 setzen!
-->  null1,null2,null3,null4,1,2,3,4,5,10

**Comment by CE7** [comment]
Wir sollten einfach eine Sortierung durchführen. Sollte es dann nach der Sortierung Felder geben, bei denen der SQL-Index -1 ist. Lassen wir eine Fehlermeldung aufpoppen!

**Comment by janiak-minova** [comment]
Manche Masken haben Feldern, die nicht ans CAS geschickt werden sollen.
Für diese Fälle kann ein negativer SQL-Index angegeben werden, diese Felder werden dann aussortiert, siehe #867
