### ISSUE TITLE
Umsetzten von Konsole und SuperUser Modus?

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#861]
In der Version 11 kann eine Konsole angezeigt werden, die auch einige Eingaben erlaubt. Unter anderem das aktivieren des SuperUser Modus. 

Einige Masken (z.B. `Invoice`) haben Abschnitte, die nur anzuzeigen sind, wenn der SuperUser Modus aktiviert ist.

- [x] Soll eine Konsole geöffnet werden können? Was soll dort an Ausgaben angezeigt werden? Was für Eingaben sind möglich?
- [x] Soll SuperUser Modus verwendet werden können? Wenn ja wie wird er aktiviert?

<img width="1792" alt="Bildschirmfoto 2021-09-13 um 11 13 25" src="https://user-images.githubusercontent.com/77741125/133057507-480aa144-fb63-4270-9f05-861a97893935.png">

**Comment by ingraban** [comment]
Der Super-User Modus kann über den Befehl su aktiviert werden. Wir benötigen kein Kennwort. Die Funktionen selbst sind ja immer mit einem Berechtigungskonzept belegt. Viellicht können wir deshalb auch den SuperUser Modus als als "Erweiterte Darstellung" in den Einstellungen aktivierter gestalten.

**Comment by janiak-minova** [comment]
Die Konsole wird vorerst nicht umgesetzt. 

Um Sections in Masken anzuzeigen, die bisher nur für SuperUser sichtbar sind, werden die Einstellungen um einen "Experten Modus" erweitert.
