### ISSUE TITLE
Fehler wenn kein ":" im Format der Uhrzeit

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#865]
Wenn in den Einstellungen bei dem Uhrzeitsformat kein ":" gegeben ist, können Uhrzeiten nicht per Hand eingetragen werden (Wenn Zeichen einzeln getippt werden).

<img width="768" alt="Bildschirmfoto 2021-09-13 um 16 06 12" src="https://user-images.githubusercontent.com/77741125/133098356-c2e15601-b7af-4f3e-9087-0ec9d5243c84.png">

**Comment by Bauer-David** [comment]
Entscheidung durch Wilfried: Alle ungültigen Zeichen für die Formatierung der Zeit sollen unterbunden werden. Zusätzlich sollen dann die Tests ergänzt werden für die Eingabe der verschiedenen Zeichen.

**Comment by janiak-minova** [comment]
Bei dem Zeitformat sollten auch Formate mit am/pm bei der Eingabe zu unterstützt werden.

**Comment by Bauer-David** [comment]
> Bei dem Zeitformat sollten auch Formate mit am/pm bei der Eingabe zu unterstützt werden.

Kannst du es genauer beschreiben. Soll nur die am/pm angezeigt werden oder soll konkret aktiviert werden, ob die Zeiten in 12 Stunden oder 24 Stunden Format angezeigt werden. Oder genügt die Umsetzung aus #888, die wie folgt aussieht: Wenn bei den Timepattern hh eingegeben wird, verwenden wird das 12 Stunden Format, bei HH verwenden wird 24 Stunden. Genügt das?

**Comment by janiak-minova** [comment]
Wenn als Format "hh:mm a" gegeben ist, soll auch eine Eingabe per Hand von "7:15 pm" möglich sein, was in unserem Zeitformat 19:15 entspricht. Wahrscheinlich funktioniert das auch automatisch, sollte aber auf jeden Fall getestet werden. 
Es sollte immer erkannt werden, wenn das Datum oder die Zeit wie im Pattern gegeben ausgeschrieben wird

Prinzipiell fallen mir folgende Sonderfälle ein, die beachtet werden müssen:
- "Besondere" Trennzeichen wie ".", "?", "*" da diese in Regex besondere Bedeutungen haben
- Mehr als ein Trennzeichen
- Trennzeichen am Anfang/Ende
- Vertauschen der Reihenfolge, vor allem MM/dd/yyyy ist ja recht verbreitet  (*)
- Zeitformate mit am/pm

(*) Hier sollte dann auch die Eingabe ohne Trennzeichen funktionieren. Also be gegebenem Format MM/dd/yyyy muss die Eingabe 02012021 zu 1. Februar 2021 ausgewertet werden
