### ISSUE TITLE
Icon Größen in den Preferences anpassen

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.rcp#894]
Wir brauchen nur noch 4 Varianten; 
@2x varianten sind dann eine Größe größer wie die normalen Icons

* s --> 16x16, toolbar ist 24x24
* m --> 24x24, toolbar ist 32x32
* l --> 32x32, toolbar ist 48x48
* xl --> 48x48, toolbar ist 64x64

Die Größeneinstellungen für die Icon und die Schriftgröße soll zusammengefasst werden.

Dabei soll #399 mit beachtet werden.

**Comment by janiak-minova** [comment]
Wurde mit #908 und #901 gelöst.
