### ISSUE TITLE
Icon Skalierung in Part-Toolbar unter Windows

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#911]
Unter Windows haben wir das Problem, dass die Icons immer die gesamte Part-Toolbar einnehmen, auch wenn sie nur in einer kleineren Auflösung vorhanden sind. Entsprechen sehen sie dann sehr verschwommen aus. Komischerweise hat das Icon der Parts selbst (z.B. bei Details) die korrekte Größe.

Größe S unter Windows:
![2dc44e97-c157-4bf6-ac89-8cad6a24c48d](https://user-images.githubusercontent.com/77741125/135593011-3f584854-77be-459a-b325-a01639aae588.jpg)

Zum Vergleich Größe S unter Mac:
<img width="382" alt="Bildschirmfoto 2021-10-01 um 10 40 00" src="https://user-images.githubusercontent.com/77741125/135593102-6c0a5366-da48-4293-ba32-bf684b148cc3.png">

Das beste wäre es, die Part-Toolbar insgesamt in der Höhe zu reduzieren, wenn kleinere Bilder gewählt sind. Dann sähe das auch unter Mac besser aus.

**Comment by splitcells** [comment]
Konnte ich auch nachstellen:
![grafik](https://user-images.githubusercontent.com/7956931/135844503-5b12d5df-610e-42b2-8488-400292469bb5.png)

**Comment by CE7** [comment]
Die Toolbar sollte dann auch an die Größe angepasst werden. (Siehe S unter MAC) Dort haben wir viel zu viel "Freiraum"
