### ISSUE TITLE
Seltsames Verhalten von Datumsfeld

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#927]
Zum Nachstellen, in den Einstellungen ist kein Datumsformat gegeben:

1. Eingeben von "0", Verlassen des Feldes mit Tab
<img width="142" alt="Bildschirmfoto 2021-10-11 um 15 23 56" src="https://user-images.githubusercontent.com/77741125/136797821-502ff09c-eb9d-4e37-ac31-479e9d1a4605.png">

2. Zurück ins Feld, letze Ziffer löschen, Verlassen des Feldes mit Tab
<img width="136" alt="Bildschirmfoto 2021-10-11 um 15 24 02" src="https://user-images.githubusercontent.com/77741125/136797840-20997071-ed04-4634-9f56-2beda000e458.png">

Das Datum hat sich verändert, von der Jahreszahl sind nur 3 Ziffern zu sehen.

**Comment by Bauer-David** [comment]
Das Verhalten ist richtig, das die eingäbe mit der Ausgabe übereinstimmt. Nach dem Löschen der letzten Zahl ändert sich der Input von 11102021 zu 1110202, da wir bei dem Datum die Aufteilung nach Länge bestimmen, werden hier die letzten vier Zahlen für das Jahr genommen. Dabei ist es nicht relevant, ob das Datum mit oder ohne Trennzeichen eingegeben wurde.
