### ISSUE TITLE
Images in den Einstellungen über ImageUtil laden

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#952]
Aktuell liegen die Images, die in den Einstellungen genutzt werden, in einem eigenen Ordner im preferencewindow Plugin und werden auch aus diesem geladen.

Um das einheitlicher zu gestalten sollten die Images über die Klasse ImageUtil geladen werden.
Das ist vor allem wichtig, wenn die Einstellungen über Helper erweitert werden, damit die Images aus dem vom CAS geladenen Ordner genutzt werden können.
Außerdem werden dann die Bild-Größen entsprechend der Einstellungen angepasst.

**Comment by Bauer-David** [comment]
Das Info Symbol für Tooltips im PreferenceWindow ist zu groß.

<img width="1034" alt="Bildschirmfoto 2022-02-14 um 08 23 43" src="https://user-images.githubusercontent.com/61147549/153818393-ddba661c-15c6-4d8d-a7cb-46ad09b122fc.png">
