### ISSUE TITLE
Ausgewählte Zelle in Grids springt 

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#967]
Zum Nachstellen: 

1. Scrollen nach rechts sodass die erste Spalte nur teilweise zu sehen ist

 <img width="696" alt="Bildschirmfoto 2021-11-02 um 17 00 18" src="https://user-images.githubusercontent.com/77741125/139892628-20f637bc-f740-45cf-9ab2-d2c321df99fd.png">

2. Auswählen eines Feldes außerhalb des Grids

3. Klicken auf eine Zelle im Grid -> Geklickt wurde auf "Beschreibung", ausgewählt ist "Mwst", im Grid wurde nach links gescrollt sodass die erste Spalte komplett zu sehen ist

<img width="710" alt="Bildschirmfoto 2021-11-02 um 17 00 30" src="https://user-images.githubusercontent.com/77741125/139892669-19ff4f1c-24d0-4a3c-8bf7-b63b406f9c9c.png">

Ansatzpunkt: Der Fokuslistener für die Nattable in der Klasse `SectionGrid`

**Comment by Bauer-David** [comment]
Wird nun zusammengefasst in dem Issue #1144 bearbeitet
